# Wrangling and Cleaning of all raw data

In [1]:
# importing packages
import pandas as pd
import os

### 1. Wrangling External Data

Let us first analyze the format of all external datasets:

In [2]:
electricity_access = pd.read_csv("../data/external/electricity-access.csv", skiprows =4)

In [3]:
electricity_access

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,99.900000,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,33.903800,38.854624,40.199898,43.017148,44.381259,46.264875,48.100862,48.711995,NaN,NaN
2,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,71.500000,97.700000,97.700000,93.400000,97.700000,97.700000,97.700000,85.300000,NaN,NaN
3,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,46.758739,50.906115,48.789457,51.211055,51.168083,51.730899,54.224724,55.437577,NaN,NaN
4,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,42.000000,41.800000,42.900000,45.300000,45.600000,47.000000,48.200000,48.500000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.400000,68.900000,79.200000,62.000000,72.800000,73.900000,74.900000,76.000000,NaN,NaN
263,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.300000,83.900000,84.400000,84.700000,85.000000,90.000000,89.300000,86.500000,NaN,NaN
264,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.100000,35.400000,40.300000,40.200000,43.000000,44.600000,46.700000,47.800000,NaN,NaN
265,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,33.700000,42.500000,44.000000,45.400000,46.700000,52.700000,49.000000,50.100000,NaN,NaN

In [4]:
electricity_access.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', 'Unnamed: 68'],
      dtype='object')

Let's see a couple other datasets too:

In [5]:
fdi = pd.read_csv("../data/external/fdi.csv", skiprows =4)
fdi

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.907264,0.923398,5.253373,4.399822,-2.215283,6.294368,4.303487,7.000585,NaN,NaN
1,Africa Eastern and Southern,AFE,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.195805,2.017779,1.076353,1.337747,1.497207,1.481455,5.038473,1.718270,NaN,NaN
2,Afghanistan,AFG,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.884000,0.516606,0.274797,0.661572,0.124496,0.064994,0.144401,NaN,NaN,NaN
3,Africa Western and Central,AFW,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.033252,2.013496,2.575635,2.016799,1.511376,1.448811,2.008478,1.738454,NaN,NaN
4,Angola,AGO,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,11.081339,-0.340243,-10.038377,-8.125891,-5.780813,-3.848264,-6.548542,-6.320564,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.453604,3.648046,3.994494,4.043060,3.608747,5.113617,5.321433,8.168575,NaN,NaN
262,"Yemen, Rep.",YEM,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.036388,-1.791312,-1.005319,-1.305638,-1.694944,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.438736,0.684613,0.539674,1.374291,1.314078,0.932200,9.677949,2.268806,NaN,NaN
264,Zambia,ZMB,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.447417,3.162520,4.280501,1.552319,2.350919,1.351906,1.784078,-0.223287,NaN,NaN
265,Zimbabwe,ZWE,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.999687,1.669274,1.746885,2.101721,1.142806,0.699034,0.881174,1.247870,NaN,NaN

Now we need all these metrics specifically for India. So first we will create a dataframe.

In [6]:
combined_economic_indicators = pd.DataFrame(columns=electricity_access.columns)

In [7]:
# combined_economic_indicators.columns = electricity_access.columns
combined_economic_indicators

Empty DataFrame
Columns: [Country Name, Country Code, Indicator Name, Indicator Code, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, Unnamed: 68]
Index: []

[0 rows x 69 columns]

In [8]:
india_row = electricity_access[electricity_access["Country Name"] == "India"]

In [9]:
combined_economic_indicators = pd.concat([combined_economic_indicators, india_row], ignore_index=True)

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\98932846.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_economic_indicators = pd.concat([combined_economic_indicators, india_row], ignore_index=True)

In [10]:
combined_economic_indicators

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,India,IND,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,88.0,89.6,91.8,95.7,95.9,96.5,99.6,99.2,NaN,NaN

Since all these datasets are of the same format, we can append only the data pertaining to India from each dataset to this dataframe using an iterator.

In [11]:
external_data_files = os.listdir("../data/external/")

In [12]:
for file in external_data_files:
    df = pd.read_csv(f"../data/external/{file}", skiprows=4)
    print(file)
    india_row = df[df["Country Name"] == "India"]
    combined_economic_indicators = pd.concat([combined_economic_indicators, india_row], ignore_index=True)
    # combined_economic_indicators = pd.concat([combined_economic_indicators, df], ignore_index=True)

electricity-access.csv
FDI.csv
gdp growth.csv
gdp-per-capita.csv
gdp.csv
gov-debt.csv
inflation.csv
net-migration.csv
poverty-headcount.csv
SPI.csv
unemployment.csv
women-parliament.csv

In [13]:
combined_economic_indicators

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,India,IND,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.800000e+01,8.960000e+01,9.180000e+01,9.570000e+01,9.590000e+01,9.650000e+01,9.960000e+01,9.920000e+01,NaN,NaN
1,India,IND,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.800000e+01,8.960000e+01,9.180000e+01,9.570000e+01,9.590000e+01,9.650000e+01,9.960000e+01,9.920000e+01,NaN,NaN
2,India,IND,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.092115e+00,1.937364e+00,1.507316e+00,1.558215e+00,1.784826e+00,2.406203e+00,1.412171e+00,1.489211e+00,NaN,NaN
3,India,IND,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,3.722743e+00,2.931128e+00,5.994353e+00,7.452950e+00,-2.635770e+00,...,7.996254e+00,8.256306e+00,6.795383e+00,6.453851e+00,3.871437e+00,-5.777725e+00,9.689592e+00,6.987039e+00,7.583971e+00,NaN
4,India,IND,GDP per capita (current US$),NY.GDP.PCAP.CD,8.303510e+01,8.596970e+01,9.027687e+01,1.013152e+02,1.154876e+02,1.190850e+02,...,1.590174e+03,1.714280e+03,1.957970e+03,1.974378e+03,2.050164e+03,1.915552e+03,2.250179e+03,2.366310e+03,2.484845e+03,NaN
5,India,IND,GDP (current US$),NY.GDP.MKTP.CD,3.702988e+10,3.923244e+10,4.216148e+10,4.842192e+10,5.648029e+10,5.955611e+10,...,2.103588e+12,2.294797e+12,2.651474e+12,2.702930e+12,2.835606e+12,2.674852e+12,3.167271e+12,3.353470e+12,3.549919e+12,NaN
6,India,IND,"Central government debt, total (% of GDP)",GC.DOD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.996472e+01,4.763376e+01,4.758361e+01,4.652250e+01,NaN,NaN,NaN,NaN,NaN,NaN
7,India,IND,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.779878e+00,1.695213e+00,3.632215e+00,2.946161e+00,1.335526e+01,9.474759e+00,...,4.906973e+00,4.948216e+00,3.328173e+00,3.938826e+00,3.729506e+00,6.623437e+00,5.131407e+00,6.699034e+00,5.649143e+00,NaN
8,India,IND,Net migration,SM.POP.NETM,5.226400e+04,1.141810e+05,1.103980e+05,4.898600e+04,5.837000e+03,1.907700e+04,...,-4.750940e+05,6.811900e+04,-2.196560e+05,-5.615630e+05,-5.934950e+05,-3.477200e+04,-3.019700e+05,-4.873030e+05,-4.861360e+05,NaN
9,India,IND,Poverty headcount ratio at $2.15 a day (2017 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,1.880000e+01,1.810000e+01,1.340000e+01,1.110000e+01,1.320000e+01,1.550000e+01,1.290000e+01,NaN,NaN,NaN
10,India,IND,Statistical performance indicators (SPI): Over...,IQ.SPI.OVRL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.738542e+01,6.466250e+01,6.908208e+01,7.036708e+01,7.265542e+01,7.525458e+01,7.419625e+01,NaN,NaN
11,India,IND,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.894000e+00,7.800000e+00,7.723000e+00,7.652000e+00,6.510000e+00,7.859000e+00,6.380000e+00,4.822000e+00,4.172000e+00,NaN
12,India,IND,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.197053e+01,1.197053e+01,1.180812e+01,1.180812e+01,1.439114e+01,1.436464e+01,1.444444e+01,1.494465e+01,1.524164e+01,NaN

In [14]:
combined_economic_indicators = combined_economic_indicators.drop(index = 0)
combined_economic_indicators = combined_economic_indicators.reset_index(drop=True)
combined_economic_indicators

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,India,IND,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.800000e+01,8.960000e+01,9.180000e+01,9.570000e+01,9.590000e+01,9.650000e+01,9.960000e+01,9.920000e+01,NaN,NaN
1,India,IND,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.092115e+00,1.937364e+00,1.507316e+00,1.558215e+00,1.784826e+00,2.406203e+00,1.412171e+00,1.489211e+00,NaN,NaN
2,India,IND,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,3.722743e+00,2.931128e+00,5.994353e+00,7.452950e+00,-2.635770e+00,...,7.996254e+00,8.256306e+00,6.795383e+00,6.453851e+00,3.871437e+00,-5.777725e+00,9.689592e+00,6.987039e+00,7.583971e+00,NaN
3,India,IND,GDP per capita (current US$),NY.GDP.PCAP.CD,8.303510e+01,8.596970e+01,9.027687e+01,1.013152e+02,1.154876e+02,1.190850e+02,...,1.590174e+03,1.714280e+03,1.957970e+03,1.974378e+03,2.050164e+03,1.915552e+03,2.250179e+03,2.366310e+03,2.484845e+03,NaN
4,India,IND,GDP (current US$),NY.GDP.MKTP.CD,3.702988e+10,3.923244e+10,4.216148e+10,4.842192e+10,5.648029e+10,5.955611e+10,...,2.103588e+12,2.294797e+12,2.651474e+12,2.702930e+12,2.835606e+12,2.674852e+12,3.167271e+12,3.353470e+12,3.549919e+12,NaN
5,India,IND,"Central government debt, total (% of GDP)",GC.DOD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.996472e+01,4.763376e+01,4.758361e+01,4.652250e+01,NaN,NaN,NaN,NaN,NaN,NaN
6,India,IND,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.779878e+00,1.695213e+00,3.632215e+00,2.946161e+00,1.335526e+01,9.474759e+00,...,4.906973e+00,4.948216e+00,3.328173e+00,3.938826e+00,3.729506e+00,6.623437e+00,5.131407e+00,6.699034e+00,5.649143e+00,NaN
7,India,IND,Net migration,SM.POP.NETM,5.226400e+04,1.141810e+05,1.103980e+05,4.898600e+04,5.837000e+03,1.907700e+04,...,-4.750940e+05,6.811900e+04,-2.196560e+05,-5.615630e+05,-5.934950e+05,-3.477200e+04,-3.019700e+05,-4.873030e+05,-4.861360e+05,NaN
8,India,IND,Poverty headcount ratio at $2.15 a day (2017 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,1.880000e+01,1.810000e+01,1.340000e+01,1.110000e+01,1.320000e+01,1.550000e+01,1.290000e+01,NaN,NaN,NaN
9,India,IND,Statistical performance indicators (SPI): Over...,IQ.SPI.OVRL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.738542e+01,6.466250e+01,6.908208e+01,7.036708e+01,7.265542e+01,7.525458e+01,7.419625e+01,NaN,NaN
10,India,IND,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.894000e+00,7.800000e+00,7.723000e+00,7.652000e+00,6.510000e+00,7.859000e+00,6.380000e+00,4.822000e+00,4.172000e+00,NaN
11,India,IND,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.197053e+01,1.197053e+01,1.180812e+01,1.180812e+01,1.439114e+01,1.436464e+01,1.444444e+01,1.494465e+01,1.524164e+01,NaN

### Cleaning external data:

In [15]:
combined_economic_indicators = combined_economic_indicators.drop(columns = ["Country Name", "Country Code","Indicator Code", "Unnamed: 68"])
combined_economic_indicators

,Indicator Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Access to electricity (% of population),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.510000e+01,8.800000e+01,8.960000e+01,9.180000e+01,9.570000e+01,9.590000e+01,9.650000e+01,9.960000e+01,9.920000e+01,NaN
1,"Foreign direct investment, net inflows (% of GDP)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.695660e+00,2.092115e+00,1.937364e+00,1.507316e+00,1.558215e+00,1.784826e+00,2.406203e+00,1.412171e+00,1.489211e+00,NaN
2,GDP growth (annual %),NaN,3.722743e+00,2.931128e+00,5.994353e+00,7.452950e+00,-2.635770e+00,-5.532877e-02,7.825963e+00,3.387929e+00,...,7.410228e+00,7.996254e+00,8.256306e+00,6.795383e+00,6.453851e+00,3.871437e+00,-5.777725e+00,9.689592e+00,6.987039e+00,7.583971e+00
3,GDP per capita (current US$),8.303510e+01,8.596970e+01,9.027687e+01,1.013152e+02,1.154876e+02,1.190850e+02,8.920135e+01,9.604633e+01,9.951684e+01,...,1.559864e+03,1.590174e+03,1.714280e+03,1.957970e+03,1.974378e+03,2.050164e+03,1.915552e+03,2.250179e+03,2.366310e+03,2.484845e+03
4,GDP (current US$),3.702988e+10,3.923244e+10,4.216148e+10,4.842192e+10,5.648029e+10,5.955611e+10,4.558123e+10,5.013494e+10,5.308546e+10,...,2.039126e+12,2.103588e+12,2.294797e+12,2.651474e+12,2.702930e+12,2.835606e+12,2.674852e+12,3.167271e+12,3.353470e+12,3.549919e+12
5,"Central government debt, total (% of GDP)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.990092e+01,4.996472e+01,4.763376e+01,4.758361e+01,4.652250e+01,NaN,NaN,NaN,NaN,NaN
6,"Inflation, consumer prices (annual %)",1.779878e+00,1.695213e+00,3.632215e+00,2.946161e+00,1.335526e+01,9.474759e+00,1.080185e+01,1.306220e+01,3.237412e+00,...,6.665657e+00,4.906973e+00,4.948216e+00,3.328173e+00,3.938826e+00,3.729506e+00,6.623437e+00,5.131407e+00,6.699034e+00,5.649143e+00
7,Net migration,5.226400e+04,1.141810e+05,1.103980e+05,4.898600e+04,5.837000e+03,1.907700e+04,-1.448070e+05,-1.243360e+05,-1.843260e+05,...,-3.106940e+05,-4.750940e+05,6.811900e+04,-2.196560e+05,-5.615630e+05,-5.934950e+05,-3.477200e+04,-3.019700e+05,-4.873030e+05,-4.861360e+05
8,Poverty headcount ratio at $2.15 a day (2017 P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.880000e+01,1.810000e+01,1.340000e+01,1.110000e+01,1.320000e+01,1.550000e+01,1.290000e+01,NaN,NaN
9,Statistical performance indicators (SPI): Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.738542e+01,6.466250e+01,6.908208e+01,7.036708e+01,7.265542e+01,7.525458e+01,7.419625e+01,NaN
10,"Unemployment, total (% of total labor force) (...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.992000e+00,7.894000e+00,7.800000e+00,7.723000e+00,7.652000e+00,6.510000e+00,7.859000e+00,6.380000e+00,4.822000e+00,4.172000e+00
11,Proportion of seats held by women in national ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.141805e+01,1.197053e+01,1.197053e+01,1.180812e+01,1.180812e+01,1.439114e+01,1.436464e+01,1.444444e+01,1.494465e+01,1.524164e+01

In [16]:
#exporting this dataframe to a csv file
combined_economic_indicators.to_csv('../data/processed/combined_economic_indicators.csv', index=False)

In [17]:
df = pd.read_csv("../data/processed/combined_economic_indicators.csv")
df

,Indicator Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Access to electricity (% of population),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.510000e+01,8.800000e+01,8.960000e+01,9.180000e+01,9.570000e+01,9.590000e+01,9.650000e+01,9.960000e+01,9.920000e+01,NaN
1,"Foreign direct investment, net inflows (% of GDP)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.695660e+00,2.092115e+00,1.937364e+00,1.507316e+00,1.558215e+00,1.784826e+00,2.406203e+00,1.412171e+00,1.489211e+00,NaN
2,GDP growth (annual %),NaN,3.722743e+00,2.931128e+00,5.994353e+00,7.452950e+00,-2.635770e+00,-5.532877e-02,7.825963e+00,3.387929e+00,...,7.410228e+00,7.996254e+00,8.256306e+00,6.795383e+00,6.453851e+00,3.871437e+00,-5.777725e+00,9.689592e+00,6.987039e+00,7.583971e+00
3,GDP per capita (current US$),8.303510e+01,8.596970e+01,9.027687e+01,1.013152e+02,1.154876e+02,1.190850e+02,8.920135e+01,9.604633e+01,9.951684e+01,...,1.559864e+03,1.590174e+03,1.714280e+03,1.957970e+03,1.974378e+03,2.050164e+03,1.915552e+03,2.250179e+03,2.366310e+03,2.484845e+03
4,GDP (current US$),3.702988e+10,3.923244e+10,4.216148e+10,4.842192e+10,5.648029e+10,5.955611e+10,4.558123e+10,5.013494e+10,5.308546e+10,...,2.039126e+12,2.103588e+12,2.294797e+12,2.651474e+12,2.702930e+12,2.835606e+12,2.674852e+12,3.167271e+12,3.353470e+12,3.549919e+12
5,"Central government debt, total (% of GDP)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.990092e+01,4.996472e+01,4.763376e+01,4.758361e+01,4.652250e+01,NaN,NaN,NaN,NaN,NaN
6,"Inflation, consumer prices (annual %)",1.779878e+00,1.695213e+00,3.632215e+00,2.946161e+00,1.335526e+01,9.474759e+00,1.080185e+01,1.306220e+01,3.237412e+00,...,6.665657e+00,4.906973e+00,4.948216e+00,3.328173e+00,3.938826e+00,3.729506e+00,6.623437e+00,5.131407e+00,6.699034e+00,5.649143e+00
7,Net migration,5.226400e+04,1.141810e+05,1.103980e+05,4.898600e+04,5.837000e+03,1.907700e+04,-1.448070e+05,-1.243360e+05,-1.843260e+05,...,-3.106940e+05,-4.750940e+05,6.811900e+04,-2.196560e+05,-5.615630e+05,-5.934950e+05,-3.477200e+04,-3.019700e+05,-4.873030e+05,-4.861360e+05
8,Poverty headcount ratio at $2.15 a day (2017 P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.880000e+01,1.810000e+01,1.340000e+01,1.110000e+01,1.320000e+01,1.550000e+01,1.290000e+01,NaN,NaN
9,Statistical performance indicators (SPI): Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.738542e+01,6.466250e+01,6.908208e+01,7.036708e+01,7.265542e+01,7.525458e+01,7.419625e+01,NaN
10,"Unemployment, total (% of total labor force) (...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.992000e+00,7.894000e+00,7.800000e+00,7.723000e+00,7.652000e+00,6.510000e+00,7.859000e+00,6.380000e+00,4.822000e+00,4.172000e+00
11,Proportion of seats held by women in national ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.141805e+01,1.197053e+01,1.197053e+01,1.180812e+01,1.180812e+01,1.439114e+01,1.436464e+01,1.444444e+01,1.494465e+01,1.524164e+01

### 2. Wrangling and cleaning candidate list of 2019 and 2024:

In [18]:
# Loading datasets
cand_list_2019 = pd.read_csv("../data/raw/all_turnout_2019.csv")
cand_list_2024 = pd.read_csv("../data/raw/all_turnout_2024.csv")

In [19]:
cand_list_2019

,State Name,PC NAME,CANDIDATES NAME,SEX,AGE,CATEGORY,PARTY NAME,PARTY SYMBOL,GENERAL,POSTAL,TOTAL,OVER TOTAL ELECTORS IN CONSTITUENCY,OVER TOTAL VOTES POLLED IN CONSTITUENCY,Total Electors
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,23.294530,31.356893,1451418
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1.231003,1.657060,1451418
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,38.733845,52.139840,1451418
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1.221564,1.644354,1451418
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49.0,ST,JnP,Glass Tumbler,42245,549,42794,2.948427,3.968894,1451418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57.0,GENERAL,IND,Slate,870,0,870,0.089377,0.110002,973410
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32.0,GENERAL,IND,Bat,2546,0,2546,0.261555,0.321914,973410
8594,Puducherry,Puducherry,RAMESH.D,MALE,49.0,SC,IND,Mike,1653,0,1653,0.169815,0.209004,973410
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74.0,GENERAL,IND,Whistle,641,1,642,0.065954,0.081174,973410
8596,Puducherry,Puducherry,NOTA,NaN,NaN,NaN,NOTA,NaN,12192,7,12199,1.253223,1.542430,973410

In [20]:
cand_list_2019.columns

Index([' State Name ', ' PC NAME ', ' CANDIDATES NAME ', ' SEX ', ' AGE ',
       ' CATEGORY ', ' PARTY NAME ', ' PARTY SYMBOL ', ' GENERAL ', ' POSTAL ',
       ' TOTAL ', 'OVER TOTAL ELECTORS IN CONSTITUENCY',
       'OVER TOTAL VOTES POLLED IN CONSTITUENCY', 'Total Electors'],
      dtype='object')

Columns have unwanted spaces so let's rename them.

In [21]:
cand_list_2019.rename(columns={
    ' State Name ': 'State',
    ' PC NAME ' : 'Constituency',
    ' CANDIDATES NAME ' : 'Candidate', 
    ' SEX ': 'Gender',
    ' AGE ': 'Age',
    ' CATEGORY ': 'Category',
    ' PARTY NAME ': 'Party',
    ' PARTY SYMBOL ': 'Party Symbol',
    ' GENERAL ': 'General Votes',
    ' POSTAL ': 'Postal Votes',
    ' TOTAL ': 'Total Votes',
    'OVER TOTAL ELECTORS IN CONSTITUENCY': 'Over Total Electors in Constituency (%)',
    'OVER TOTAL VOTES POLLED IN CONSTITUENCY': 'Over Total Votes Polled in Constituency (%)'},
    inplace=True
)
cand_list_2019

,State,Constituency,Candidate,Gender,Age,Category,Party,Party Symbol,General Votes,Postal Votes,Total Votes,Over Total Electors in Constituency (%),Over Total Votes Polled in Constituency (%),Total Electors
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,23.294530,31.356893,1451418
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1.231003,1.657060,1451418
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,38.733845,52.139840,1451418
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1.221564,1.644354,1451418
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49.0,ST,JnP,Glass Tumbler,42245,549,42794,2.948427,3.968894,1451418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57.0,GENERAL,IND,Slate,870,0,870,0.089377,0.110002,973410
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32.0,GENERAL,IND,Bat,2546,0,2546,0.261555,0.321914,973410
8594,Puducherry,Puducherry,RAMESH.D,MALE,49.0,SC,IND,Mike,1653,0,1653,0.169815,0.209004,973410
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74.0,GENERAL,IND,Whistle,641,1,642,0.065954,0.081174,973410
8596,Puducherry,Puducherry,NOTA,NaN,NaN,NaN,NOTA,NaN,12192,7,12199,1.253223,1.542430,973410

In [22]:
cand_list_2019['Gender'].value_counts()

Gender
MALE      7322
FEMALE     726
THIRD        6
Name: count, dtype: int64

In [23]:
cand_list_2019['Category'].value_counts()

Category
GENERAL    5317
SC         2110
ST          627
Name: count, dtype: int64

The sum of all genders and categories doesn't equal to the total number of rows in the dataframe. On careful inspection I found that some rows had null values in the Gender and Category column and NOTA in the Candidate column. Let's remove all the rows with null values.

In [24]:
nota_rows = cand_list_2019[cand_list_2019['Candidate'] == 'NOTA']
nota_rows

,State,Constituency,Candidate,Gender,Age,Category,Party,Party Symbol,General Votes,Postal Votes,Total Votes,Over Total Electors in Constituency (%),Over Total Votes Polled in Constituency (%),Total Electors
10,Andhra Pradesh,Aruku,NOTA,NaN,NaN,NaN,NOTA,NaN,47955,22,47977,3.305526,4.449587,1451418
20,Andhra Pradesh,Srikakulam,NOTA,NaN,NaN,NaN,NOTA,NaN,25500,45,25545,1.643970,2.194049,1553860
35,Andhra Pradesh,Vizianagaram,NOTA,NaN,NaN,NaN,NOTA,NaN,29468,33,29501,1.961529,2.413302,1503980
50,Andhra Pradesh,Visakhapatnam,NOTA,NaN,NaN,NaN,NOTA,NaN,16626,20,16646,0.909966,1.342505,1829300
61,Andhra Pradesh,Anakapalli,NOTA,NaN,NaN,NaN,NOTA,NaN,34877,20,34897,2.293798,2.813240,1521363
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,NCT OF Delhi,NORTH WEST DELHI,NOTA,NaN,NaN,NaN,NOTA,NaN,10199,11,10210,0.429173,0.727734,2378995
8542,NCT OF Delhi,WEST DELHI,NOTA,NaN,NaN,NaN,NOTA,NaN,8883,54,8937,0.376827,0.619553,2371644
8570,NCT OF Delhi,SOUTH DELHI,NOTA,NaN,NaN,NaN,NOTA,NaN,5247,17,5264,0.254612,0.433413,2067463
8577,Lakshadweep,Lakshadweep,NOTA,NaN,NaN,NaN,NOTA,NaN,99,1,100,0.181196,0.212648,55189
8596,Puducherry,Puducherry,NOTA,NaN,NaN,NaN,NOTA,NaN,12192,7,12199,1.253223,1.542430,973410

We need to remove these 543 rows.

In [25]:
cand_list_2019 = cand_list_2019[cand_list_2019['Candidate'] != 'NOTA']

In [26]:
cand_list_2019

,State,Constituency,Candidate,Gender,Age,Category,Party,Party Symbol,General Votes,Postal Votes,Total Votes,Over Total Electors in Constituency (%),Over Total Votes Polled in Constituency (%),Total Electors
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,23.294530,31.356893,1451418
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1.231003,1.657060,1451418
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,38.733845,52.139840,1451418
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1.221564,1.644354,1451418
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49.0,ST,JnP,Glass Tumbler,42245,549,42794,2.948427,3.968894,1451418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8591,Puducherry,Puducherry,N. TAMIZH MARANE,MALE,46.0,GENERAL,IND,Gift Pack,4785,6,4791,0.492187,0.605769,973410
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57.0,GENERAL,IND,Slate,870,0,870,0.089377,0.110002,973410
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32.0,GENERAL,IND,Bat,2546,0,2546,0.261555,0.321914,973410
8594,Puducherry,Puducherry,RAMESH.D,MALE,49.0,SC,IND,Mike,1653,0,1653,0.169815,0.209004,973410
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74.0,GENERAL,IND,Whistle,641,1,642,0.065954,0.081174,973410

All values in 'Age' column are floating points. Let's convert them to integers.

In [27]:
type(cand_list_2019['Age'])

pandas.core.series.Series

In [28]:
cand_list_2019['Age'] = cand_list_2019['Age'].fillna(0).astype(int)

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\3516005529.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cand_list_2019['Age'] = cand_list_2019['Age'].fillna(0).astype(int)

In [29]:
cand_list_2019

,State,Constituency,Candidate,Gender,Age,Category,Party,Party Symbol,General Votes,Postal Votes,Total Votes,Over Total Electors in Constituency (%),Over Total Votes Polled in Constituency (%),Total Electors
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72,ST,TDP,Bicycle,336163,1938,338101,23.294530,31.356893,1451418
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54,ST,BJP,Lotus,17578,289,17867,1.231003,1.657060,1451418
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26,ST,YSRCP,Ceiling Fan,557561,4629,562190,38.733845,52.139840,1451418
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46,ST,INC,Hand,17656,74,17730,1.221564,1.644354,1451418
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49,ST,JnP,Glass Tumbler,42245,549,42794,2.948427,3.968894,1451418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8591,Puducherry,Puducherry,N. TAMIZH MARANE,MALE,46,GENERAL,IND,Gift Pack,4785,6,4791,0.492187,0.605769,973410
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57,GENERAL,IND,Slate,870,0,870,0.089377,0.110002,973410
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32,GENERAL,IND,Bat,2546,0,2546,0.261555,0.321914,973410
8594,Puducherry,Puducherry,RAMESH.D,MALE,49,SC,IND,Mike,1653,0,1653,0.169815,0.209004,973410
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74,GENERAL,IND,Whistle,641,1,642,0.065954,0.081174,973410

Let us now see the 2024 candidate list dataset.

In [30]:
cand_list_2024 = pd.read_csv("../data/raw/all_turnout_2024.csv")

In [31]:
cand_list_2024

,election_year,state_name,constituency_name,constituency_type,party_name,candidate_name,EVM_votes,postal_votes,total_votes,rank,units
0,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Bharatiya Janata Party,BISHNU PADA RAY,102182.0,254.0,102436.0,1,"EVM_votes, postal_votes, total_votes in absolu..."
1,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Indian National Congress,KULDEEP RAI SHARMA,77829.0,211.0,78040.0,2,"EVM_votes, postal_votes, total_votes in absolu..."
2,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Andaman Nicobar Democratic Congress,MANOJ PAUL,8236.0,18.0,8254.0,3,"EVM_votes, postal_votes, total_votes in absolu..."
3,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Communist Party of India (Marxist),D AYYAPPAN,6009.0,8.0,6017.0,4,"EVM_votes, postal_votes, total_votes in absolu..."
4,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Independent,V.K. ABDUL AZIZ,2195.0,8.0,2203.0,5,"EVM_votes, postal_votes, total_votes in absolu..."
...,...,...,...,...,...,...,...,...,...,...,...
8897,2024,West Bengal,Birbhum,General,Independent,ABDUL IMRAN,3823.0,9.0,3832.0,10,"EVM_votes, postal_votes, total_votes in absolu..."
8898,2024,West Bengal,Birbhum,General,All India Arya Mahasabha,BISWAJIT MISHRA,3806.0,17.0,3823.0,11,"EVM_votes, postal_votes, total_votes in absolu..."
8899,2024,West Bengal,Birbhum,General,Bharatiya National Janata Dal,MD. JAKIR HOSSAIN,2547.0,10.0,2557.0,12,"EVM_votes, postal_votes, total_votes in absolu..."
8900,2024,West Bengal,Birbhum,General,Indian National Socialistic Action Forces,DOLA SARKAR,2027.0,6.0,2033.0,13,"EVM_votes, postal_votes, total_votes in absolu..."
8901,2024,West Bengal,Birbhum,General,None of the Above,NOTA,14037.0,56.0,14093.0,4,"EVM_votes, postal_votes, total_votes in absolu..."

Renaming the columns:

In [32]:
print(cand_list_2019.columns)
print(cand_list_2024.columns)

Index(['State', 'Constituency', 'Candidate', 'Gender', 'Age', 'Category',
       'Party', 'Party Symbol', 'General Votes', 'Postal Votes', 'Total Votes',
       'Over Total Electors in Constituency (%)',
       'Over Total Votes Polled in Constituency (%)', 'Total Electors'],
      dtype='object')
Index(['election_year', 'state_name', 'constituency_name', 'constituency_type',
       'party_name', 'candidate_name', 'EVM_votes', 'postal_votes',
       'total_votes', 'rank', 'units'],
      dtype='object')

In [33]:
cand_list_2024.rename(columns={
    'election_year':'Year',
    'state_name': 'State', 
    'constituency_name': 'Constituency', 
    'constituency_type':'Category',
    'party_name': 'Party', 
    'candidate_name': 'Candidate',  
    'EVM_votes':'EVM Votes',
    'postal_votes': 'Postal Votes',
    'total_votes': 'Total Votes',
    'rank' : 'Rank',     
    'units': 'Units'
    },inplace=True
)
cand_list_2024

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units
0,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Bharatiya Janata Party,BISHNU PADA RAY,102182.0,254.0,102436.0,1,"EVM_votes, postal_votes, total_votes in absolu..."
1,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Indian National Congress,KULDEEP RAI SHARMA,77829.0,211.0,78040.0,2,"EVM_votes, postal_votes, total_votes in absolu..."
2,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Andaman Nicobar Democratic Congress,MANOJ PAUL,8236.0,18.0,8254.0,3,"EVM_votes, postal_votes, total_votes in absolu..."
3,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Communist Party of India (Marxist),D AYYAPPAN,6009.0,8.0,6017.0,4,"EVM_votes, postal_votes, total_votes in absolu..."
4,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Independent,V.K. ABDUL AZIZ,2195.0,8.0,2203.0,5,"EVM_votes, postal_votes, total_votes in absolu..."
...,...,...,...,...,...,...,...,...,...,...,...
8897,2024,West Bengal,Birbhum,General,Independent,ABDUL IMRAN,3823.0,9.0,3832.0,10,"EVM_votes, postal_votes, total_votes in absolu..."
8898,2024,West Bengal,Birbhum,General,All India Arya Mahasabha,BISWAJIT MISHRA,3806.0,17.0,3823.0,11,"EVM_votes, postal_votes, total_votes in absolu..."
8899,2024,West Bengal,Birbhum,General,Bharatiya National Janata Dal,MD. JAKIR HOSSAIN,2547.0,10.0,2557.0,12,"EVM_votes, postal_votes, total_votes in absolu..."
8900,2024,West Bengal,Birbhum,General,Indian National Socialistic Action Forces,DOLA SARKAR,2027.0,6.0,2033.0,13,"EVM_votes, postal_votes, total_votes in absolu..."
8901,2024,West Bengal,Birbhum,General,None of the Above,NOTA,14037.0,56.0,14093.0,4,"EVM_votes, postal_votes, total_votes in absolu..."

In [34]:
cand_list_2024['Year'].value_counts()

Year
2024    8902
Name: count, dtype: int64

In [35]:
cand_list_2024['Category'].value_counts()

Category
General            7192
Scheduled Caste    1216
Scheduled Tribe     494
Name: count, dtype: int64

Removing NOTA values.

In [36]:
cand_list_2024 = cand_list_2024[cand_list_2024['Candidate'] != 'NOTA']

In [37]:
cand_list_2024

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units
0,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Bharatiya Janata Party,BISHNU PADA RAY,102182.0,254.0,102436.0,1,"EVM_votes, postal_votes, total_votes in absolu..."
1,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Indian National Congress,KULDEEP RAI SHARMA,77829.0,211.0,78040.0,2,"EVM_votes, postal_votes, total_votes in absolu..."
2,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Andaman Nicobar Democratic Congress,MANOJ PAUL,8236.0,18.0,8254.0,3,"EVM_votes, postal_votes, total_votes in absolu..."
3,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Communist Party of India (Marxist),D AYYAPPAN,6009.0,8.0,6017.0,4,"EVM_votes, postal_votes, total_votes in absolu..."
4,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Independent,V.K. ABDUL AZIZ,2195.0,8.0,2203.0,5,"EVM_votes, postal_votes, total_votes in absolu..."
...,...,...,...,...,...,...,...,...,...,...,...
8896,2024,West Bengal,Birbhum,General,Independent,SAURAV MUDI,4249.0,7.0,4256.0,9,"EVM_votes, postal_votes, total_votes in absolu..."
8897,2024,West Bengal,Birbhum,General,Independent,ABDUL IMRAN,3823.0,9.0,3832.0,10,"EVM_votes, postal_votes, total_votes in absolu..."
8898,2024,West Bengal,Birbhum,General,All India Arya Mahasabha,BISWAJIT MISHRA,3806.0,17.0,3823.0,11,"EVM_votes, postal_votes, total_votes in absolu..."
8899,2024,West Bengal,Birbhum,General,Bharatiya National Janata Dal,MD. JAKIR HOSSAIN,2547.0,10.0,2557.0,12,"EVM_votes, postal_votes, total_votes in absolu..."
8900,2024,West Bengal,Birbhum,General,Indian National Socialistic Action Forces,DOLA SARKAR,2027.0,6.0,2033.0,13,"EVM_votes, postal_votes, total_votes in absolu..."

Now there is one problem with this dataset. It doesn't have age and gender fields of the contesting candidates. 
Let's look at another raw dataset that we have:

In [38]:
cands = pd.read_csv("../data/raw/candidates_list_2024.csv")

In [39]:
cands

,Candidate Name,Party,Age,Gender,State,Constituency,Constituency_No
0,V.K. ABDUL AZIZ,Independent,42,M,Andaman & Nicobar Islands,Andaman & Nicobar Islands,1
1,USHA KUMARI,Independent,39,F,Andaman & Nicobar Islands,Andaman & Nicobar Islands,1
2,RINKU MALA MONDAL,Independent,36,F,Andaman & Nicobar Islands,Andaman & Nicobar Islands,1
3,KULDEEP RAI SHARMA,Indian National Congress,56,M,Andaman & Nicobar Islands,Andaman & Nicobar Islands,1
4,ANAND RAMNATH ARLEKAR,Independent,58,M,Andaman & Nicobar Islands,Andaman & Nicobar Islands,1
...,...,...,...,...,...,...,...
8436,SATABDI ROY,All India Trinamool Congress,55,F,West Bengal,Birbhum,42
8437,DOLA SARKAR,Indian National Socialistic Action Forces,49,F,West Bengal,Birbhum,42
8438,SAURAV MUDI,Independent,43,M,West Bengal,Birbhum,42
8439,RAJNATH SARKAR,Bahujan Samaj Party,68,M,West Bengal,Birbhum,42
8440,AYESHA KHATUN,Socialist Unity Centre Of India (COMMUNIST),53,F,West Bengal,Birbhum,42

Let's observe their common fields and run some operation to retrieve the Gender and Age of the candidates from `cands`.

In [40]:
cand_list_2024.columns

Index(['Year', 'State', 'Constituency', 'Category', 'Party', 'Candidate',
       'EVM Votes', 'Postal Votes', 'Total Votes', 'Rank', 'Units'],
      dtype='object')

In [41]:
cands.columns

Index(['Candidate Name', 'Party', 'Age', 'Gender', 'State', 'Constituency',
       'Constituency_No'],
      dtype='object')

In [42]:
import numpy as np
import pandas as pd
from fuzzywuzzy import fuzz
from tqdm import tqdm
import os

# Function to clean and standardize names
def clean_name(name):
    name = str(name).lower()
    name = name.replace('.', ' ').replace(',', ' ')
    name = ' '.join(name.split())  # Remove extra spaces
    return name

# Identify the correct column names for candidate names
candidate_col_2024 = 'Candidate' if 'Candidate' in cand_list_2024.columns else input("Enter the column name for candidate names in cand_list_2024: ")
candidate_col_cands = 'Candidate Name' if 'Candidate Name' in cands.columns else input("Enter the column name for candidate names in cands: ")

# Path to the output CSV file
output_path = '../data/outputs/name-matching-output.csv'

# Check if the output file already exists
if os.path.exists(output_path):
    # If file exists, load the data
    cand_list_2024 = pd.read_csv(output_path)
else:
    # Apply name cleaning to both datasets
    cand_list_2024['Clean_Candidate'] = cand_list_2024[candidate_col_2024].apply(clean_name)
    cands['Clean_Candidate'] = cands[candidate_col_cands].apply(clean_name)

    # Function to find the best match
    def find_best_match(name, state, constituency, candidates):
        best_match = None
        best_score = 0
        for _, row in candidates.iterrows():
            if row['State'] == state and row['Constituency'] == constituency:
                score = fuzz.token_set_ratio(name, row['Clean_Candidate'])
                if score > best_score:
                    best_score = score
                    best_match = row
        return best_match if best_score > 80 else None

    # Create a dictionary to store matches
    matches = {}

    # Find matches for each candidate
    for _, row in tqdm(cand_list_2024.iterrows(), total=len(cand_list_2024)):
        key = (row['Clean_Candidate'], row['State'], row['Constituency'])
        if key not in matches:
            match = find_best_match(row['Clean_Candidate'], row['State'], row['Constituency'], cands)
            matches[key] = match

    # Function to get age and gender from matches
    def get_age_gender(clean_name, state, constituency):
        match = matches.get((clean_name, state, constituency))
        return pd.Series({'Age': match['Age'] if match is not None else np.nan,
                          'Gender': match['Gender'] if match is not None else np.nan})

    # Add Age and Gender columns to cand_list_2024
    cand_list_2024 = cand_list_2024.copy()  # Create a copy to ensure we're not working with a slice
    cand_list_2024[['Age', 'Gender']] = cand_list_2024.apply(
        lambda row: get_age_gender(row['Clean_Candidate'], row['State'], row['Constituency']), axis=1
    )

    # Remove the temporary 'Clean_Candidate' column
    cand_list_2024 = cand_list_2024.drop('Clean_Candidate', axis=1)

    # Save the output to the desired path
    cand_list_2024.to_csv(output_path, index=False)

c:\Users\ujjwa\miniconda3\envs\manthan\Lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [43]:
cand_list_2024

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units,Age,Gender
0,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Bharatiya Janata Party,BISHNU PADA RAY,102182.0,254.0,102436.0,1,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
1,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Indian National Congress,KULDEEP RAI SHARMA,77829.0,211.0,78040.0,2,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
2,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Andaman Nicobar Democratic Congress,MANOJ PAUL,8236.0,18.0,8254.0,3,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
3,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Communist Party of India (Marxist),D AYYAPPAN,6009.0,8.0,6017.0,4,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
4,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Independent,V.K. ABDUL AZIZ,2195.0,8.0,2203.0,5,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8355,2024,West Bengal,Birbhum,General,Independent,SAURAV MUDI,4249.0,7.0,4256.0,9,"EVM_votes, postal_votes, total_votes in absolu...",43.0,M
8356,2024,West Bengal,Birbhum,General,Independent,ABDUL IMRAN,3823.0,9.0,3832.0,10,"EVM_votes, postal_votes, total_votes in absolu...",36.0,M
8357,2024,West Bengal,Birbhum,General,All India Arya Mahasabha,BISWAJIT MISHRA,3806.0,17.0,3823.0,11,"EVM_votes, postal_votes, total_votes in absolu...",40.0,M
8358,2024,West Bengal,Birbhum,General,Bharatiya National Janata Dal,MD. JAKIR HOSSAIN,2547.0,10.0,2557.0,12,"EVM_votes, postal_votes, total_votes in absolu...",55.0,M
8359,2024,West Bengal,Birbhum,General,Indian National Socialistic Action Forces,DOLA SARKAR,2027.0,6.0,2033.0,13,"EVM_votes, postal_votes, total_votes in absolu...",49.0,F

Let's save this for now as csv. We'll concatenate 2019 list with it later after cleaning.

In [44]:
cand_list_2024.to_csv('../data/processed/candidate_list_turnout.csv', index=False)

Now some names that couldn't be matched have NaN values in their age and gender columns. Let's find them.

In [45]:
null_values = cand_list_2024[cand_list_2024['Gender'].isnull()]

In [46]:
null_values

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units,Age,Gender
0,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Bharatiya Janata Party,BISHNU PADA RAY,102182.0,254.0,102436.0,1,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
1,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Indian National Congress,KULDEEP RAI SHARMA,77829.0,211.0,78040.0,2,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
2,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Andaman Nicobar Democratic Congress,MANOJ PAUL,8236.0,18.0,8254.0,3,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
3,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Communist Party of India (Marxist),D AYYAPPAN,6009.0,8.0,6017.0,4,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
4,2024,Andaman and Nicobar Islands,Andaman & Nicobar Islands,General,Independent,V.K. ABDUL AZIZ,2195.0,8.0,2203.0,5,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7834,2024,Uttarakhand,Nainital-udhamsingh Nagar,General,Independent,RAMESH KUMAR MAX,3271.0,29.0,3300.0,7,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
7835,2024,Uttarakhand,Nainital-udhamsingh Nagar,General,Peoples Party of India (Democratic),AMAR SINGH SAINI,2963.0,24.0,2987.0,8,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
7836,2024,Uttarakhand,Nainital-udhamsingh Nagar,General,Bharat Ki Lok Jimmedar Party,JEEVAN CHANDRA UPRETI,2292.0,18.0,2310.0,9,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
7837,2024,Uttarakhand,Nainital-udhamsingh Nagar,General,Uttarakhand Kranti Dal,SHIB SINGH,1809.0,46.0,1855.0,10,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN
7838,2024,Uttarakhand,Nainital-udhamsingh Nagar,General,Bhartiya Shakti Chetna Party,SURENDRA SINGH,1655.0,18.0,1673.0,11,"EVM_votes, postal_votes, total_votes in absolu...",NaN,NaN

So there are 2444 rows with nulls. Let's try to get intuition as to what is causing this.

In [47]:
null_values['State'].unique()

array(['Andaman and Nicobar Islands', 'Chhattisgarh',
       'Dadra Nagar Haveli Daman Diu', 'Delhi', 'Haryana',
       'Himachal Pradesh', 'Jammu and Kashmir', 'Madhya Pradesh',
       'Maharashtra', 'Manipur', 'Mizoram', 'Puducherry', 'Rajasthan',
       'Tamil Nadu', 'Telangana', 'Uttarakhand'], dtype=object)

In [48]:
null_values['Constituency'].unique()

array(['Andaman & Nicobar Islands', 'Raigarh', 'Janjgir-Champa', 'Korba',
       'Bilaspur', 'Rajnandgaon', 'Durg', 'Raipur', 'Mahasamund',
       'Bastar', 'Kanker', 'Daman & Diu', 'Dadar & Nagar Haveli',
       'Chandni Chowk', 'North-East Delhi', 'East Delhi', 'New Delhi',
       'North-West Delhi', 'West Delhi', 'South Delhi', 'Ambala',
       'Kurukshetra', 'Sirsa', 'Hisar', 'Karnal', 'Sonipat', 'Rohtak',
       'Bhiwani-Mahendragarh', 'Gurgaon', 'Faridabad', 'Kangra', 'Mandi',
       'Hamirpur', 'Shimla', 'Baramulla', 'Srinagar', 'Udhampur', 'Jammu',
       'Morena', 'Bhind', 'Gwalior', 'Guna', 'Sagar', 'Tikamgarh',
       'Damoh', 'Khajuraho', 'Satna', 'Rewa', 'Sidhi', 'Shahdol',
       'Jabalpur', 'Mandla', 'Balaghat', 'Chhindwara', 'Hoshangabad',
       'Vidisha', 'Bhopal', 'Rajgarh', 'Dewas', 'Ujjain', 'Mandsour',
       'Ratlam', 'Dhar', 'Indore', 'Khargone', 'Khandwa', 'Betul',
       'Ratnagiri- Sindhudurg', 'Mumbai North central',
       'Mumbai South central', 'Inner manipur', 'Outer manipur',
       'Mizoram', 'Puducherry', 'Ganganagar', 'Churu', 'Jhunjhunu',
       'Sikar', 'Jaipur Rural', 'Jaipur', 'Alwar', 'Bharatpur',
       'Karauli-Dholpur', 'Dausa', 'Tonk-Sawai Madhopur', 'Ajmer',
       'Nagaur', 'Pali', 'Jodhpur', 'Barmer', 'Jalore', 'Udaipur',
       'Banswara', 'Chittorgarh', 'Rajsamand', 'Bhilwara', 'Kota',
       'Jhalawar-Baran', 'Chennai North', 'Chennai South',
       'Chennai central', 'Sriperumbudur', 'Kancheepuram', 'Arakkonam',
       'Vellore', 'Krishnagiri', 'Dharmapuri', 'Tiruvannamalai', 'Arani',
       'Viluppuram', 'Kallakurichi', 'Salem', 'Namakkal', 'Erode',
       'Tiruppur', 'Nilgiris', 'Coimbatore', 'Pollachi', 'Dindigul',
       'Karur', 'Tiruchirappalli', 'Perambalur', 'Cuddalore',
       'Chidambaram', 'Mayiladuthurai', 'Nagapattinam', 'Sivaganga',
       'Madurai', 'Theni', 'Virudhunagar', 'Ramanathapuram',
       'Thoothukkudi', 'Tenkasi', 'Tirunelveli', 'Kanniyakumari',
       'Thanjavur', 'CHEVELLA', 'Nainital-udhamsingh Nagar'], dtype=object)

The problem seems to be that there is a mismatch between the constituency names between both the datasets, `cand_list_2024` and `cands`. We can fix this manually too but let us try and eliminate the null values step by step. First, we will drop all the nulls from the original cand_list_2024. The idea is we already have `null_values`, we can fill in missing data in this dataframe first and then later concatenate it with the `cand_list_2024`.

In [49]:
cand_list_2024 = cand_list_2024.dropna(subset=['Gender'])

Second, we will fill missing data in all those constituencies which have a case mismatch.

In [50]:

# Function to standardize constituency names
def standardize_constituency(name):
    return str(name).strip().upper()

# Standardize constituency names for null_values and cands
null_values['Constituency'] = null_values['Constituency'].apply(standardize_constituency)
cands['Constituency'] = cands['Constituency'].apply(standardize_constituency)

# Function to find the best match
def find_match(row):
    matches = cands[(cands['State'] == row['State']) & (cands['Constituency'] == row['Constituency'])]
    if not matches.empty:
        return matches.iloc[0]
    return pd.Series({'Age': None, 'Gender': None})

# Find matches for null values
matches = null_values.apply(find_match, axis=1)

# Update the null values with matched data
null_values['Age'] = matches['Age']
null_values['Gender'] = matches['Gender']

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\3189194290.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  null_values['Constituency'] = null_values['Constituency'].apply(standardize_constituency)
C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\3189194290.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  null_values['Age'] = matches['Age']
C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\3189194290.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  null_values['Gender'] = matches['Gender']

In [51]:
null_values

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units,Age,Gender
0,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Bharatiya Janata Party,BISHNU PADA RAY,102182.0,254.0,102436.0,1,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
1,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Indian National Congress,KULDEEP RAI SHARMA,77829.0,211.0,78040.0,2,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
2,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Andaman Nicobar Democratic Congress,MANOJ PAUL,8236.0,18.0,8254.0,3,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
3,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Communist Party of India (Marxist),D AYYAPPAN,6009.0,8.0,6017.0,4,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
4,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Independent,V.K. ABDUL AZIZ,2195.0,8.0,2203.0,5,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7834,2024,Uttarakhand,NAINITAL-UDHAMSINGH NAGAR,General,Independent,RAMESH KUMAR MAX,3271.0,29.0,3300.0,7,"EVM_votes, postal_votes, total_votes in absolu...",54.0,M
7835,2024,Uttarakhand,NAINITAL-UDHAMSINGH NAGAR,General,Peoples Party of India (Democratic),AMAR SINGH SAINI,2963.0,24.0,2987.0,8,"EVM_votes, postal_votes, total_votes in absolu...",54.0,M
7836,2024,Uttarakhand,NAINITAL-UDHAMSINGH NAGAR,General,Bharat Ki Lok Jimmedar Party,JEEVAN CHANDRA UPRETI,2292.0,18.0,2310.0,9,"EVM_votes, postal_votes, total_votes in absolu...",54.0,M
7837,2024,Uttarakhand,NAINITAL-UDHAMSINGH NAGAR,General,Uttarakhand Kranti Dal,SHIB SINGH,1809.0,46.0,1855.0,10,"EVM_votes, postal_votes, total_votes in absolu...",54.0,M
7838,2024,Uttarakhand,NAINITAL-UDHAMSINGH NAGAR,General,Bhartiya Shakti Chetna Party,SURENDRA SINGH,1655.0,18.0,1673.0,11,"EVM_votes, postal_votes, total_votes in absolu...",54.0,M

As you can see some data has been filled, yet we still have some empty values. Third, repeat the same procedure for this `null_values` dataframe now.

In [52]:
more_nulls = null_values[null_values['Gender'].isnull()]

In [53]:
more_nulls

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units,Age,Gender
0,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Bharatiya Janata Party,BISHNU PADA RAY,102182.0,254.0,102436.0,1,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
1,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Indian National Congress,KULDEEP RAI SHARMA,77829.0,211.0,78040.0,2,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
2,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Andaman Nicobar Democratic Congress,MANOJ PAUL,8236.0,18.0,8254.0,3,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
3,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Communist Party of India (Marxist),D AYYAPPAN,6009.0,8.0,6017.0,4,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
4,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Independent,V.K. ABDUL AZIZ,2195.0,8.0,2203.0,5,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3584,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Samaj Party,AAYARE RAJENDRA LAHU,7796.0,60.0,7856.0,6,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
3585,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,SHAKIL SAWANT,6373.0,22.0,6395.0,7,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
3586,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,TAMBADE AMRUT ANANT (RAJAPURKAR),5563.0,19.0,5582.0,8,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
3587,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Mukti Party,ASHOK GANGARAM PAWAR,5244.0,36.0,5280.0,9,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None
3588,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Sainik Samaj Party,SURESH GOVINDRAO SHINDE,2209.0,38.0,2247.0,10,"EVM_votes, postal_votes, total_votes in absolu...",NaN,None

The number of rows with missing data have decreased drastically. Let us now fix these rows with missing data.

In [54]:
null_values = null_values.dropna(subset=['Gender'])

In [55]:
null_values

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units,Age,Gender
1149,2024,Chhattisgarh,RAIGARH,Scheduled Tribe,Bharatiya Janata Party,RADHESHYAM RATHIYA,806667.0,1608.0,808275.0,1,"EVM_votes, postal_votes, total_votes in absolu...",33.0,M
1150,2024,Chhattisgarh,RAIGARH,Scheduled Tribe,Indian National Congress,DR. MENKA DEVI SINGH,566487.0,1397.0,567884.0,2,"EVM_votes, postal_votes, total_votes in absolu...",33.0,M
1151,2024,Chhattisgarh,RAIGARH,Scheduled Tribe,Bahujan Samaj Party,INNOCENT KUJUR - BIDANA ORAON,15493.0,107.0,15600.0,3,"EVM_votes, postal_votes, total_votes in absolu...",33.0,M
1152,2024,Chhattisgarh,RAIGARH,Scheduled Tribe,Hamar Raj Party,ALBERT MING,10915.0,44.0,10959.0,5,"EVM_votes, postal_votes, total_votes in absolu...",33.0,M
1153,2024,Chhattisgarh,RAIGARH,Scheduled Tribe,Independent,PRAKASH KUMAR URANW,7719.0,3.0,7722.0,6,"EVM_votes, postal_votes, total_votes in absolu...",33.0,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7834,2024,Uttarakhand,NAINITAL-UDHAMSINGH NAGAR,General,Independent,RAMESH KUMAR MAX,3271.0,29.0,3300.0,7,"EVM_votes, postal_votes, total_votes in absolu...",54.0,M
7835,2024,Uttarakhand,NAINITAL-UDHAMSINGH NAGAR,General,Peoples Party of India (Democratic),AMAR SINGH SAINI,2963.0,24.0,2987.0,8,"EVM_votes, postal_votes, total_votes in absolu...",54.0,M
7836,2024,Uttarakhand,NAINITAL-UDHAMSINGH NAGAR,General,Bharat Ki Lok Jimmedar Party,JEEVAN CHANDRA UPRETI,2292.0,18.0,2310.0,9,"EVM_votes, postal_votes, total_votes in absolu...",54.0,M
7837,2024,Uttarakhand,NAINITAL-UDHAMSINGH NAGAR,General,Uttarakhand Kranti Dal,SHIB SINGH,1809.0,46.0,1855.0,10,"EVM_votes, postal_votes, total_votes in absolu...",54.0,M
7838,2024,Uttarakhand,NAINITAL-UDHAMSINGH NAGAR,General,Bhartiya Shakti Chetna Party,SURENDRA SINGH,1655.0,18.0,1673.0,11,"EVM_votes, postal_votes, total_votes in absolu...",54.0,M

In [56]:
more_nulls['Constituency'].unique()

array(['ANDAMAN & NICOBAR ISLANDS', 'DAMAN & DIU', 'DADAR & NAGAR HAVELI',
       'CHANDNI CHOWK', 'NORTH-EAST DELHI', 'EAST DELHI', 'NEW DELHI',
       'NORTH-WEST DELHI', 'WEST DELHI', 'SOUTH DELHI',
       'RATNAGIRI- SINDHUDURG'], dtype=object)

In [57]:
cands = pd.read_csv("../data/raw/candidates-2024.csv")

In [58]:
# Find matches for null values
matches = more_nulls.apply(find_match, axis=1)

# Update the null values with matched data
more_nulls['Age'] = matches['Age']
more_nulls['Gender'] = matches['Gender']

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\1818482249.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  more_nulls['Age'] = matches['Age']
C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\1818482249.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  more_nulls['Gender'] = matches['Gender']

In [59]:
more_nulls

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units,Age,Gender
0,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Bharatiya Janata Party,BISHNU PADA RAY,102182.0,254.0,102436.0,1,"EVM_votes, postal_votes, total_votes in absolu...",None,None
1,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Indian National Congress,KULDEEP RAI SHARMA,77829.0,211.0,78040.0,2,"EVM_votes, postal_votes, total_votes in absolu...",None,None
2,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Andaman Nicobar Democratic Congress,MANOJ PAUL,8236.0,18.0,8254.0,3,"EVM_votes, postal_votes, total_votes in absolu...",None,None
3,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Communist Party of India (Marxist),D AYYAPPAN,6009.0,8.0,6017.0,4,"EVM_votes, postal_votes, total_votes in absolu...",None,None
4,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Independent,V.K. ABDUL AZIZ,2195.0,8.0,2203.0,5,"EVM_votes, postal_votes, total_votes in absolu...",None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3584,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Samaj Party,AAYARE RAJENDRA LAHU,7796.0,60.0,7856.0,6,"EVM_votes, postal_votes, total_votes in absolu...",None,None
3585,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,SHAKIL SAWANT,6373.0,22.0,6395.0,7,"EVM_votes, postal_votes, total_votes in absolu...",None,None
3586,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,TAMBADE AMRUT ANANT (RAJAPURKAR),5563.0,19.0,5582.0,8,"EVM_votes, postal_votes, total_votes in absolu...",None,None
3587,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Mukti Party,ASHOK GANGARAM PAWAR,5244.0,36.0,5280.0,9,"EVM_votes, postal_votes, total_votes in absolu...",None,None
3588,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Sainik Samaj Party,SURESH GOVINDRAO SHINDE,2209.0,38.0,2247.0,10,"EVM_votes, postal_votes, total_votes in absolu...",None,None

In [60]:
more_nulls['State'].unique()

array(['Andaman and Nicobar Islands', 'Dadra Nagar Haveli Daman Diu',
       'Delhi', 'Maharashtra'], dtype=object)

In [61]:
more_nulls['Constituency'].unique()

array(['ANDAMAN & NICOBAR ISLANDS', 'DAMAN & DIU', 'DADAR & NAGAR HAVELI',
       'CHANDNI CHOWK', 'NORTH-EAST DELHI', 'EAST DELHI', 'NEW DELHI',
       'NORTH-WEST DELHI', 'WEST DELHI', 'SOUTH DELHI',
       'RATNAGIRI- SINDHUDURG'], dtype=object)

Another case of case mismatch.

In [62]:
more_nulls['State'].unique()

array(['Andaman and Nicobar Islands', 'Dadra Nagar Haveli Daman Diu',
       'Delhi', 'Maharashtra'], dtype=object)

In [63]:
cands['State'].unique()

array(['Andaman & Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh',
       'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh',
       'Dadra & Nagar Haveli and Daman & Diu', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh',
       'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland',
       'NCT OF Delhi', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan',
       'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
       'Uttarakhand', 'West Bengal'], dtype=object)

In [64]:
# Filter the dataframe for rows where 'State' is Maharashtra
maharashtra_constituencies = cands[cands['State'] == 'Maharashtra']['Constituency'].unique()

# Display the unique constituency names
print(maharashtra_constituencies)

# Filter the dataframe for rows where 'State' is Maharashtra
delhi_constituencies = cands[cands['State'] == 'Delhi']['Constituency'].unique()

# Display the unique constituency names
print(delhi_constituencies)

# Filter the dataframe for rows where 'State' is Maharashtra
andaman = cands[cands['State'] == 'Andaman and Nicobar Islands']['Constituency'].unique()

# Display the unique constituency names
print(andaman)

# Filter the dataframe for rows where 'State' is Maharashtra
daman = cands[cands['State'] == 'Dadra Nagar Haveli Daman Diu']['Constituency'].unique()

# Display the unique constituency names
print(daman)

['Nandurbar' 'Dhule' 'Jalgaon' 'Raver' 'Buldhana' 'Akola' 'Amravati'
 'Wardha' 'Ramtek' 'Nagpur' 'Bhandara Gondiya' 'Gadchiroli - Chimur'
 'Chandrapur' 'Yavatmal- Washim' 'Hingoli' 'Nanded' 'Parbhani' 'Jalna'
 'Aurangabad' 'Dindori' 'Nashik' 'Palghar' 'Bhiwandi' 'Kalyan' 'Thane'
 'Mumbai North' 'Mumbai North West' 'Mumbai North East'
 'Mumbai North Central' 'Mumbai South Central' 'Mumbai South' 'Raigad'
 'Maval' 'Pune' 'Baramati' 'Shirur' 'Ahmednagar' 'Shirdi' 'Beed'
 'Osmanabad' 'Latur' 'Solapur' 'Madha' 'Sangli' 'Satara'
 'Ratnagiri-Sindhudurg' 'Kolhapur' 'Hatkanangale']
[]
[]
[]

In [65]:
# Replace 'Andaman & Nicobar Islands' with 'Andaman and Nicobar Islands' in the 'State' column
cands['State'] = cands['State'].replace('Andaman & Nicobar Islands', 'Andaman and Nicobar Islands')
cands['State'] = cands['State'].replace('NCT OF Delhi', 'Delhi')
cands['State'] = cands['State'].replace('Dadra & Nagar Haveli and Daman & Diu', 'Dadra Nagar Haveli Daman Diu')
cands['Constituency'] = cands['Constituency'].replace('Ratnagiri-Sindhudurg', 'RATNAGIRI- SINDHUDURG')
cands['Constituency'] = cands['Constituency'].replace('Chandni Chowk', 'CHANDNI CHOWK')
cands['Constituency'] = cands['Constituency'].replace('North-East Delhi', 'NORTH-EAST DELHI')
cands['Constituency'] = cands['Constituency'].replace('East Delhi', 'EAST DELHI')
cands['Constituency'] = cands['Constituency'].replace('New Delhi', 'NEW DELHI')
cands['Constituency'] = cands['Constituency'].replace('North-West Delhi', 'NORTH-WEST DELHI')
cands['Constituency'] = cands['Constituency'].replace('West Delhi', 'WEST DELHI')
cands['Constituency'] = cands['Constituency'].replace('South Delhi', 'SOUTH DELHI')
cands['Constituency'] = cands['Constituency'].replace('Andaman & Nicobar Islands', 'ANDAMAN & NICOBAR ISLANDS')
cands['Constituency'] = cands['Constituency'].replace('Daman & Diu', 'DAMAN & DIU')
cands['Constituency'] = cands['Constituency'].replace('Dadar & Nagar Haveli', 'DADAR & NAGAR HAVELI')

In [66]:
# Find matches for null values
matches = more_nulls.apply(find_match, axis=1)

# Update the null values with matched data
more_nulls['Age'] = matches['Age']
more_nulls['Gender'] = matches['Gender']

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\1818482249.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  more_nulls['Age'] = matches['Age']
C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\1818482249.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  more_nulls['Gender'] = matches['Gender']

In [67]:
more_nulls

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units,Age,Gender
0,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Bharatiya Janata Party,BISHNU PADA RAY,102182.0,254.0,102436.0,1,"EVM_votes, postal_votes, total_votes in absolu...",42,male
1,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Indian National Congress,KULDEEP RAI SHARMA,77829.0,211.0,78040.0,2,"EVM_votes, postal_votes, total_votes in absolu...",42,male
2,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Andaman Nicobar Democratic Congress,MANOJ PAUL,8236.0,18.0,8254.0,3,"EVM_votes, postal_votes, total_votes in absolu...",42,male
3,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Communist Party of India (Marxist),D AYYAPPAN,6009.0,8.0,6017.0,4,"EVM_votes, postal_votes, total_votes in absolu...",42,male
4,2024,Andaman and Nicobar Islands,ANDAMAN & NICOBAR ISLANDS,General,Independent,V.K. ABDUL AZIZ,2195.0,8.0,2203.0,5,"EVM_votes, postal_votes, total_votes in absolu...",42,male
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3584,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Samaj Party,AAYARE RAJENDRA LAHU,7796.0,60.0,7856.0,6,"EVM_votes, postal_votes, total_votes in absolu...",61,male
3585,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,SHAKIL SAWANT,6373.0,22.0,6395.0,7,"EVM_votes, postal_votes, total_votes in absolu...",61,male
3586,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,TAMBADE AMRUT ANANT (RAJAPURKAR),5563.0,19.0,5582.0,8,"EVM_votes, postal_votes, total_votes in absolu...",61,male
3587,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Mukti Party,ASHOK GANGARAM PAWAR,5244.0,36.0,5280.0,9,"EVM_votes, postal_votes, total_votes in absolu...",61,male
3588,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Sainik Samaj Party,SURESH GOVINDRAO SHINDE,2209.0,38.0,2247.0,10,"EVM_votes, postal_votes, total_votes in absolu...",61,male

In [68]:
nulls = more_nulls[more_nulls['Gender'].isnull()]

In [69]:
nulls

Empty DataFrame
Columns: [Year, State, Constituency, Category, Party, Candidate, EVM Votes, Postal Votes, Total Votes, Rank, Units, Age, Gender]
Index: []

Finally there are no rows with missing data. Now let's concatenate them one by one.

In [70]:
null_values = pd.concat([null_values, more_nulls], ignore_index=True)

In [71]:
null_values

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units,Age,Gender
0,2024,Chhattisgarh,RAIGARH,Scheduled Tribe,Bharatiya Janata Party,RADHESHYAM RATHIYA,806667.0,1608.0,808275.0,1,"EVM_votes, postal_votes, total_votes in absolu...",33.0,M
1,2024,Chhattisgarh,RAIGARH,Scheduled Tribe,Indian National Congress,DR. MENKA DEVI SINGH,566487.0,1397.0,567884.0,2,"EVM_votes, postal_votes, total_votes in absolu...",33.0,M
2,2024,Chhattisgarh,RAIGARH,Scheduled Tribe,Bahujan Samaj Party,INNOCENT KUJUR - BIDANA ORAON,15493.0,107.0,15600.0,3,"EVM_votes, postal_votes, total_votes in absolu...",33.0,M
3,2024,Chhattisgarh,RAIGARH,Scheduled Tribe,Hamar Raj Party,ALBERT MING,10915.0,44.0,10959.0,5,"EVM_votes, postal_votes, total_votes in absolu...",33.0,M
4,2024,Chhattisgarh,RAIGARH,Scheduled Tribe,Independent,PRAKASH KUMAR URANW,7719.0,3.0,7722.0,6,"EVM_votes, postal_votes, total_votes in absolu...",33.0,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2439,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Samaj Party,AAYARE RAJENDRA LAHU,7796.0,60.0,7856.0,6,"EVM_votes, postal_votes, total_votes in absolu...",61.0,male
2440,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,SHAKIL SAWANT,6373.0,22.0,6395.0,7,"EVM_votes, postal_votes, total_votes in absolu...",61.0,male
2441,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,TAMBADE AMRUT ANANT (RAJAPURKAR),5563.0,19.0,5582.0,8,"EVM_votes, postal_votes, total_votes in absolu...",61.0,male
2442,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Mukti Party,ASHOK GANGARAM PAWAR,5244.0,36.0,5280.0,9,"EVM_votes, postal_votes, total_votes in absolu...",61.0,male
2443,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Sainik Samaj Party,SURESH GOVINDRAO SHINDE,2209.0,38.0,2247.0,10,"EVM_votes, postal_votes, total_votes in absolu...",61.0,male

Finally we'll concatenate all previous null values to `cand_list_2024`

In [72]:
cand_list_2024 = pd.concat([cand_list_2024, null_values], ignore_index=True)

In [73]:
cand_list_2024

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units,Age,Gender
0,2024,Andhra Pradesh,Araku (ST),Scheduled Tribe,Yuvajana Sramika Rythu Congress Party,GUMMA THANUJA RANI,471470.0,5535.0,477005.0,1,"EVM_votes, postal_votes, total_votes in absolu...",31.0,F
1,2024,Andhra Pradesh,Araku (ST),Scheduled Tribe,Bharatiya Janata Party,KOTHAPALLI GEETHA,417113.0,9312.0,426425.0,2,"EVM_votes, postal_votes, total_votes in absolu...",53.0,F
2,2024,Andhra Pradesh,Araku (ST),Scheduled Tribe,Communist Party of India (Marxist),APPALANARASA PACHIPENTA,119016.0,4113.0,123129.0,3,"EVM_votes, postal_votes, total_votes in absolu...",41.0,M
3,2024,Andhra Pradesh,Araku (ST),Scheduled Tribe,Bahujan Samaj Party,AVASHYA LAHARI . VARAM,24858.0,892.0,25750.0,5,"EVM_votes, postal_votes, total_votes in absolu...",30.0,F
4,2024,Andhra Pradesh,Araku (ST),Scheduled Tribe,Independent,SAMAREDDY BALAKRISHNA,9493.0,42.0,9535.0,6,"EVM_votes, postal_votes, total_votes in absolu...",48.0,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8355,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Samaj Party,AAYARE RAJENDRA LAHU,7796.0,60.0,7856.0,6,"EVM_votes, postal_votes, total_votes in absolu...",61.0,male
8356,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,SHAKIL SAWANT,6373.0,22.0,6395.0,7,"EVM_votes, postal_votes, total_votes in absolu...",61.0,male
8357,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,TAMBADE AMRUT ANANT (RAJAPURKAR),5563.0,19.0,5582.0,8,"EVM_votes, postal_votes, total_votes in absolu...",61.0,male
8358,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Mukti Party,ASHOK GANGARAM PAWAR,5244.0,36.0,5280.0,9,"EVM_votes, postal_votes, total_votes in absolu...",61.0,male
8359,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Sainik Samaj Party,SURESH GOVINDRAO SHINDE,2209.0,38.0,2247.0,10,"EVM_votes, postal_votes, total_votes in absolu...",61.0,male

Let us clean this dataset now.

In [74]:
cand_list_2024['Gender'].value_counts()

Gender
M         7434
F          728
male       149
female      46
third        3
Name: count, dtype: int64

In [75]:
cand_list_2024['Gender'] = cand_list_2024['Gender'].replace({'male': 'M', 'female': 'F', 'third': 'T'})
cand_list_2024

,Year,State,Constituency,Category,Party,Candidate,EVM Votes,Postal Votes,Total Votes,Rank,Units,Age,Gender
0,2024,Andhra Pradesh,Araku (ST),Scheduled Tribe,Yuvajana Sramika Rythu Congress Party,GUMMA THANUJA RANI,471470.0,5535.0,477005.0,1,"EVM_votes, postal_votes, total_votes in absolu...",31.0,F
1,2024,Andhra Pradesh,Araku (ST),Scheduled Tribe,Bharatiya Janata Party,KOTHAPALLI GEETHA,417113.0,9312.0,426425.0,2,"EVM_votes, postal_votes, total_votes in absolu...",53.0,F
2,2024,Andhra Pradesh,Araku (ST),Scheduled Tribe,Communist Party of India (Marxist),APPALANARASA PACHIPENTA,119016.0,4113.0,123129.0,3,"EVM_votes, postal_votes, total_votes in absolu...",41.0,M
3,2024,Andhra Pradesh,Araku (ST),Scheduled Tribe,Bahujan Samaj Party,AVASHYA LAHARI . VARAM,24858.0,892.0,25750.0,5,"EVM_votes, postal_votes, total_votes in absolu...",30.0,F
4,2024,Andhra Pradesh,Araku (ST),Scheduled Tribe,Independent,SAMAREDDY BALAKRISHNA,9493.0,42.0,9535.0,6,"EVM_votes, postal_votes, total_votes in absolu...",48.0,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8355,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Samaj Party,AAYARE RAJENDRA LAHU,7796.0,60.0,7856.0,6,"EVM_votes, postal_votes, total_votes in absolu...",61.0,M
8356,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,SHAKIL SAWANT,6373.0,22.0,6395.0,7,"EVM_votes, postal_votes, total_votes in absolu...",61.0,M
8357,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Independent,TAMBADE AMRUT ANANT (RAJAPURKAR),5563.0,19.0,5582.0,8,"EVM_votes, postal_votes, total_votes in absolu...",61.0,M
8358,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Bahujan Mukti Party,ASHOK GANGARAM PAWAR,5244.0,36.0,5280.0,9,"EVM_votes, postal_votes, total_votes in absolu...",61.0,M
8359,2024,Maharashtra,RATNAGIRI- SINDHUDURG,General,Sainik Samaj Party,SURESH GOVINDRAO SHINDE,2209.0,38.0,2247.0,10,"EVM_votes, postal_votes, total_votes in absolu...",61.0,M

In [76]:
cand_list_2024['Gender'].value_counts()

Gender
M    7583
F     774
T       3
Name: count, dtype: int64

In [77]:
cand_list_2024.drop('Units', axis=1, inplace=True)

In [78]:
cand_list_2024 = cand_list_2024[['Candidate', 'State', 'Constituency', 'Party', 'Age', 'Gender', 'Category', 'EVM Votes', 'Postal Votes', 'Total Votes', 'Rank', 'Year']]

In [79]:
cand_list_2024

,Candidate,State,Constituency,Party,Age,Gender,Category,EVM Votes,Postal Votes,Total Votes,Rank,Year
0,GUMMA THANUJA RANI,Andhra Pradesh,Araku (ST),Yuvajana Sramika Rythu Congress Party,31.0,F,Scheduled Tribe,471470.0,5535.0,477005.0,1,2024
1,KOTHAPALLI GEETHA,Andhra Pradesh,Araku (ST),Bharatiya Janata Party,53.0,F,Scheduled Tribe,417113.0,9312.0,426425.0,2,2024
2,APPALANARASA PACHIPENTA,Andhra Pradesh,Araku (ST),Communist Party of India (Marxist),41.0,M,Scheduled Tribe,119016.0,4113.0,123129.0,3,2024
3,AVASHYA LAHARI . VARAM,Andhra Pradesh,Araku (ST),Bahujan Samaj Party,30.0,F,Scheduled Tribe,24858.0,892.0,25750.0,5,2024
4,SAMAREDDY BALAKRISHNA,Andhra Pradesh,Araku (ST),Independent,48.0,M,Scheduled Tribe,9493.0,42.0,9535.0,6,2024
...,...,...,...,...,...,...,...,...,...,...,...,...
8355,AAYARE RAJENDRA LAHU,Maharashtra,RATNAGIRI- SINDHUDURG,Bahujan Samaj Party,61.0,M,General,7796.0,60.0,7856.0,6,2024
8356,SHAKIL SAWANT,Maharashtra,RATNAGIRI- SINDHUDURG,Independent,61.0,M,General,6373.0,22.0,6395.0,7,2024
8357,TAMBADE AMRUT ANANT (RAJAPURKAR),Maharashtra,RATNAGIRI- SINDHUDURG,Independent,61.0,M,General,5563.0,19.0,5582.0,8,2024
8358,ASHOK GANGARAM PAWAR,Maharashtra,RATNAGIRI- SINDHUDURG,Bahujan Mukti Party,61.0,M,General,5244.0,36.0,5280.0,9,2024
8359,SURESH GOVINDRAO SHINDE,Maharashtra,RATNAGIRI- SINDHUDURG,Sainik Samaj Party,61.0,M,General,2209.0,38.0,2247.0,10,2024

In [80]:
temp_list = cand_list_2024.copy()

In [81]:
# Convert the 'Age' column from float to int in the cand_list_2024 dataframe
temp_list['Age'] = temp_list['Age'].astype(int)

# Verify the change
temp_list

,Candidate,State,Constituency,Party,Age,Gender,Category,EVM Votes,Postal Votes,Total Votes,Rank,Year
0,GUMMA THANUJA RANI,Andhra Pradesh,Araku (ST),Yuvajana Sramika Rythu Congress Party,31,F,Scheduled Tribe,471470.0,5535.0,477005.0,1,2024
1,KOTHAPALLI GEETHA,Andhra Pradesh,Araku (ST),Bharatiya Janata Party,53,F,Scheduled Tribe,417113.0,9312.0,426425.0,2,2024
2,APPALANARASA PACHIPENTA,Andhra Pradesh,Araku (ST),Communist Party of India (Marxist),41,M,Scheduled Tribe,119016.0,4113.0,123129.0,3,2024
3,AVASHYA LAHARI . VARAM,Andhra Pradesh,Araku (ST),Bahujan Samaj Party,30,F,Scheduled Tribe,24858.0,892.0,25750.0,5,2024
4,SAMAREDDY BALAKRISHNA,Andhra Pradesh,Araku (ST),Independent,48,M,Scheduled Tribe,9493.0,42.0,9535.0,6,2024
...,...,...,...,...,...,...,...,...,...,...,...,...
8355,AAYARE RAJENDRA LAHU,Maharashtra,RATNAGIRI- SINDHUDURG,Bahujan Samaj Party,61,M,General,7796.0,60.0,7856.0,6,2024
8356,SHAKIL SAWANT,Maharashtra,RATNAGIRI- SINDHUDURG,Independent,61,M,General,6373.0,22.0,6395.0,7,2024
8357,TAMBADE AMRUT ANANT (RAJAPURKAR),Maharashtra,RATNAGIRI- SINDHUDURG,Independent,61,M,General,5563.0,19.0,5582.0,8,2024
8358,ASHOK GANGARAM PAWAR,Maharashtra,RATNAGIRI- SINDHUDURG,Bahujan Mukti Party,61,M,General,5244.0,36.0,5280.0,9,2024
8359,SURESH GOVINDRAO SHINDE,Maharashtra,RATNAGIRI- SINDHUDURG,Sainik Samaj Party,61,M,General,2209.0,38.0,2247.0,10,2024

In [82]:
# Rename 'Total Votes' to 'Total Votes Received'
temp_list.rename(columns={'Total Votes': 'Total Votes Received'}, inplace=True)

# Add a new column 'Total Votes Polled' which is the sum of all votes in each constituency
temp_list['Total Votes Polled'] = temp_list.groupby('Constituency')['Total Votes Received'].transform('sum')

temp_list = temp_list[['Candidate', 'State', 'Constituency', 'Party', 'Age', 'Gender', 'Category', 'EVM Votes', 'Postal Votes', 'Total Votes Received', 'Total Votes Polled', 'Rank', 'Year']]
temp_list

,Candidate,State,Constituency,Party,Age,Gender,Category,EVM Votes,Postal Votes,Total Votes Received,Total Votes Polled,Rank,Year
0,GUMMA THANUJA RANI,Andhra Pradesh,Araku (ST),Yuvajana Sramika Rythu Congress Party,31,F,Scheduled Tribe,471470.0,5535.0,477005.0,1113975.0,1,2024
1,KOTHAPALLI GEETHA,Andhra Pradesh,Araku (ST),Bharatiya Janata Party,53,F,Scheduled Tribe,417113.0,9312.0,426425.0,1113975.0,2,2024
2,APPALANARASA PACHIPENTA,Andhra Pradesh,Araku (ST),Communist Party of India (Marxist),41,M,Scheduled Tribe,119016.0,4113.0,123129.0,1113975.0,3,2024
3,AVASHYA LAHARI . VARAM,Andhra Pradesh,Araku (ST),Bahujan Samaj Party,30,F,Scheduled Tribe,24858.0,892.0,25750.0,1113975.0,5,2024
4,SAMAREDDY BALAKRISHNA,Andhra Pradesh,Araku (ST),Independent,48,M,Scheduled Tribe,9493.0,42.0,9535.0,1113975.0,6,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8355,AAYARE RAJENDRA LAHU,Maharashtra,RATNAGIRI- SINDHUDURG,Bahujan Samaj Party,61,M,General,7796.0,60.0,7856.0,902395.0,6,2024
8356,SHAKIL SAWANT,Maharashtra,RATNAGIRI- SINDHUDURG,Independent,61,M,General,6373.0,22.0,6395.0,902395.0,7,2024
8357,TAMBADE AMRUT ANANT (RAJAPURKAR),Maharashtra,RATNAGIRI- SINDHUDURG,Independent,61,M,General,5563.0,19.0,5582.0,902395.0,8,2024
8358,ASHOK GANGARAM PAWAR,Maharashtra,RATNAGIRI- SINDHUDURG,Bahujan Mukti Party,61,M,General,5244.0,36.0,5280.0,902395.0,9,2024
8359,SURESH GOVINDRAO SHINDE,Maharashtra,RATNAGIRI- SINDHUDURG,Sainik Samaj Party,61,M,General,2209.0,38.0,2247.0,902395.0,10,2024

In [83]:
cand_list_2019

,State,Constituency,Candidate,Gender,Age,Category,Party,Party Symbol,General Votes,Postal Votes,Total Votes,Over Total Electors in Constituency (%),Over Total Votes Polled in Constituency (%),Total Electors
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72,ST,TDP,Bicycle,336163,1938,338101,23.294530,31.356893,1451418
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54,ST,BJP,Lotus,17578,289,17867,1.231003,1.657060,1451418
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26,ST,YSRCP,Ceiling Fan,557561,4629,562190,38.733845,52.139840,1451418
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46,ST,INC,Hand,17656,74,17730,1.221564,1.644354,1451418
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49,ST,JnP,Glass Tumbler,42245,549,42794,2.948427,3.968894,1451418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8591,Puducherry,Puducherry,N. TAMIZH MARANE,MALE,46,GENERAL,IND,Gift Pack,4785,6,4791,0.492187,0.605769,973410
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57,GENERAL,IND,Slate,870,0,870,0.089377,0.110002,973410
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32,GENERAL,IND,Bat,2546,0,2546,0.261555,0.321914,973410
8594,Puducherry,Puducherry,RAMESH.D,MALE,49,SC,IND,Mike,1653,0,1653,0.169815,0.209004,973410
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74,GENERAL,IND,Whistle,641,1,642,0.065954,0.081174,973410

In [84]:
print(cand_list_2019.columns)
print(temp_list.columns)

Index(['State', 'Constituency', 'Candidate', 'Gender', 'Age', 'Category',
       'Party', 'Party Symbol', 'General Votes', 'Postal Votes', 'Total Votes',
       'Over Total Electors in Constituency (%)',
       'Over Total Votes Polled in Constituency (%)', 'Total Electors'],
      dtype='object')
Index(['Candidate', 'State', 'Constituency', 'Party', 'Age', 'Gender',
       'Category', 'EVM Votes', 'Postal Votes', 'Total Votes Received',
       'Total Votes Polled', 'Rank', 'Year'],
      dtype='object')

In [85]:
cand_list_2019.drop(['Party Symbol'], axis=1, inplace=True)

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\1541597847.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cand_list_2019.drop(['Party Symbol'], axis=1, inplace=True)

In [86]:
cand_list_2019.rename(columns={'Total Votes': 'Total Votes Received', 'Total Electors' : 'Total Votes Polled'}, inplace=True)
# cand_list_2019['Candidate', 'State', 'Constituency', 'Party', 'Age', 'Gender', 'Category', 'EVM Votes', 'Postal Votes', 'Total Votes', 'Rank', 'Year']

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\1107364137.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cand_list_2019.rename(columns={'Total Votes': 'Total Votes Received', 'Total Electors' : 'Total Votes Polled'}, inplace=True)

In [87]:
cand_list_2019

,State,Constituency,Candidate,Gender,Age,Category,Party,General Votes,Postal Votes,Total Votes Received,Over Total Electors in Constituency (%),Over Total Votes Polled in Constituency (%),Total Votes Polled
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72,ST,TDP,336163,1938,338101,23.294530,31.356893,1451418
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54,ST,BJP,17578,289,17867,1.231003,1.657060,1451418
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26,ST,YSRCP,557561,4629,562190,38.733845,52.139840,1451418
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46,ST,INC,17656,74,17730,1.221564,1.644354,1451418
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49,ST,JnP,42245,549,42794,2.948427,3.968894,1451418
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8591,Puducherry,Puducherry,N. TAMIZH MARANE,MALE,46,GENERAL,IND,4785,6,4791,0.492187,0.605769,973410
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57,GENERAL,IND,870,0,870,0.089377,0.110002,973410
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32,GENERAL,IND,2546,0,2546,0.261555,0.321914,973410
8594,Puducherry,Puducherry,RAMESH.D,MALE,49,SC,IND,1653,0,1653,0.169815,0.209004,973410
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74,GENERAL,IND,641,1,642,0.065954,0.081174,973410

In [88]:
cand_list_2019['Year'] = 2019
cand_list_2019['Rank'] = np.nan
cand_list_2019

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\4051293092.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cand_list_2019['Year'] = 2019
C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\4051293092.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cand_list_2019['Rank'] = np.nan

,State,Constituency,Candidate,Gender,Age,Category,Party,General Votes,Postal Votes,Total Votes Received,Over Total Electors in Constituency (%),Over Total Votes Polled in Constituency (%),Total Votes Polled,Year,Rank
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72,ST,TDP,336163,1938,338101,23.294530,31.356893,1451418,2019,NaN
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54,ST,BJP,17578,289,17867,1.231003,1.657060,1451418,2019,NaN
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26,ST,YSRCP,557561,4629,562190,38.733845,52.139840,1451418,2019,NaN
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46,ST,INC,17656,74,17730,1.221564,1.644354,1451418,2019,NaN
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49,ST,JnP,42245,549,42794,2.948427,3.968894,1451418,2019,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8591,Puducherry,Puducherry,N. TAMIZH MARANE,MALE,46,GENERAL,IND,4785,6,4791,0.492187,0.605769,973410,2019,NaN
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57,GENERAL,IND,870,0,870,0.089377,0.110002,973410,2019,NaN
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32,GENERAL,IND,2546,0,2546,0.261555,0.321914,973410,2019,NaN
8594,Puducherry,Puducherry,RAMESH.D,MALE,49,SC,IND,1653,0,1653,0.169815,0.209004,973410,2019,NaN
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74,GENERAL,IND,641,1,642,0.065954,0.081174,973410,2019,NaN

In [89]:
temp_list['Over Total Electors in Constituency (%)'] = (temp_list['Total Votes Received'] / temp_list['Total Votes Polled']) * 100

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\1093874025.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_list['Over Total Electors in Constituency (%)'] = (temp_list['Total Votes Received'] / temp_list['Total Votes Polled']) * 100

In [90]:
temp_list

,Candidate,State,Constituency,Party,Age,Gender,Category,EVM Votes,Postal Votes,Total Votes Received,Total Votes Polled,Rank,Year,Over Total Electors in Constituency (%)
0,GUMMA THANUJA RANI,Andhra Pradesh,Araku (ST),Yuvajana Sramika Rythu Congress Party,31,F,Scheduled Tribe,471470.0,5535.0,477005.0,1113975.0,1,2024,42.820081
1,KOTHAPALLI GEETHA,Andhra Pradesh,Araku (ST),Bharatiya Janata Party,53,F,Scheduled Tribe,417113.0,9312.0,426425.0,1113975.0,2,2024,38.279584
2,APPALANARASA PACHIPENTA,Andhra Pradesh,Araku (ST),Communist Party of India (Marxist),41,M,Scheduled Tribe,119016.0,4113.0,123129.0,1113975.0,3,2024,11.053121
3,AVASHYA LAHARI . VARAM,Andhra Pradesh,Araku (ST),Bahujan Samaj Party,30,F,Scheduled Tribe,24858.0,892.0,25750.0,1113975.0,5,2024,2.311542
4,SAMAREDDY BALAKRISHNA,Andhra Pradesh,Araku (ST),Independent,48,M,Scheduled Tribe,9493.0,42.0,9535.0,1113975.0,6,2024,0.855944
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8355,AAYARE RAJENDRA LAHU,Maharashtra,RATNAGIRI- SINDHUDURG,Bahujan Samaj Party,61,M,General,7796.0,60.0,7856.0,902395.0,6,2024,0.870572
8356,SHAKIL SAWANT,Maharashtra,RATNAGIRI- SINDHUDURG,Independent,61,M,General,6373.0,22.0,6395.0,902395.0,7,2024,0.708670
8357,TAMBADE AMRUT ANANT (RAJAPURKAR),Maharashtra,RATNAGIRI- SINDHUDURG,Independent,61,M,General,5563.0,19.0,5582.0,902395.0,8,2024,0.618576
8358,ASHOK GANGARAM PAWAR,Maharashtra,RATNAGIRI- SINDHUDURG,Bahujan Mukti Party,61,M,General,5244.0,36.0,5280.0,902395.0,9,2024,0.585110
8359,SURESH GOVINDRAO SHINDE,Maharashtra,RATNAGIRI- SINDHUDURG,Sainik Samaj Party,61,M,General,2209.0,38.0,2247.0,902395.0,10,2024,0.249004

In [91]:
temp_list['Over Total Votes Polled in Constituency (%)'] = np.nan

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\3680558049.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_list['Over Total Votes Polled in Constituency (%)'] = np.nan

In [92]:
temp_list

,Candidate,State,Constituency,Party,Age,Gender,Category,EVM Votes,Postal Votes,Total Votes Received,Total Votes Polled,Rank,Year,Over Total Electors in Constituency (%),Over Total Votes Polled in Constituency (%)
0,GUMMA THANUJA RANI,Andhra Pradesh,Araku (ST),Yuvajana Sramika Rythu Congress Party,31,F,Scheduled Tribe,471470.0,5535.0,477005.0,1113975.0,1,2024,42.820081,NaN
1,KOTHAPALLI GEETHA,Andhra Pradesh,Araku (ST),Bharatiya Janata Party,53,F,Scheduled Tribe,417113.0,9312.0,426425.0,1113975.0,2,2024,38.279584,NaN
2,APPALANARASA PACHIPENTA,Andhra Pradesh,Araku (ST),Communist Party of India (Marxist),41,M,Scheduled Tribe,119016.0,4113.0,123129.0,1113975.0,3,2024,11.053121,NaN
3,AVASHYA LAHARI . VARAM,Andhra Pradesh,Araku (ST),Bahujan Samaj Party,30,F,Scheduled Tribe,24858.0,892.0,25750.0,1113975.0,5,2024,2.311542,NaN
4,SAMAREDDY BALAKRISHNA,Andhra Pradesh,Araku (ST),Independent,48,M,Scheduled Tribe,9493.0,42.0,9535.0,1113975.0,6,2024,0.855944,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8355,AAYARE RAJENDRA LAHU,Maharashtra,RATNAGIRI- SINDHUDURG,Bahujan Samaj Party,61,M,General,7796.0,60.0,7856.0,902395.0,6,2024,0.870572,NaN
8356,SHAKIL SAWANT,Maharashtra,RATNAGIRI- SINDHUDURG,Independent,61,M,General,6373.0,22.0,6395.0,902395.0,7,2024,0.708670,NaN
8357,TAMBADE AMRUT ANANT (RAJAPURKAR),Maharashtra,RATNAGIRI- SINDHUDURG,Independent,61,M,General,5563.0,19.0,5582.0,902395.0,8,2024,0.618576,NaN
8358,ASHOK GANGARAM PAWAR,Maharashtra,RATNAGIRI- SINDHUDURG,Bahujan Mukti Party,61,M,General,5244.0,36.0,5280.0,902395.0,9,2024,0.585110,NaN
8359,SURESH GOVINDRAO SHINDE,Maharashtra,RATNAGIRI- SINDHUDURG,Sainik Samaj Party,61,M,General,2209.0,38.0,2247.0,902395.0,10,2024,0.249004,NaN

In [93]:
combined_df = pd.concat([cand_list_2019, temp_list], ignore_index=True)

In [94]:
combined_df

,State,Constituency,Candidate,Gender,Age,Category,Party,General Votes,Postal Votes,Total Votes Received,Over Total Electors in Constituency (%),Over Total Votes Polled in Constituency (%),Total Votes Polled,Year,Rank,EVM Votes
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72,ST,TDP,336163.0,1938.0,338101.0,23.294530,31.356893,1451418.0,2019,NaN,NaN
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54,ST,BJP,17578.0,289.0,17867.0,1.231003,1.657060,1451418.0,2019,NaN,NaN
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26,ST,YSRCP,557561.0,4629.0,562190.0,38.733845,52.139840,1451418.0,2019,NaN,NaN
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46,ST,INC,17656.0,74.0,17730.0,1.221564,1.644354,1451418.0,2019,NaN,NaN
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49,ST,JnP,42245.0,549.0,42794.0,2.948427,3.968894,1451418.0,2019,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16409,Maharashtra,RATNAGIRI- SINDHUDURG,AAYARE RAJENDRA LAHU,M,61,General,Bahujan Samaj Party,NaN,60.0,7856.0,0.870572,NaN,902395.0,2024,6.0,7796.0
16410,Maharashtra,RATNAGIRI- SINDHUDURG,SHAKIL SAWANT,M,61,General,Independent,NaN,22.0,6395.0,0.708670,NaN,902395.0,2024,7.0,6373.0
16411,Maharashtra,RATNAGIRI- SINDHUDURG,TAMBADE AMRUT ANANT (RAJAPURKAR),M,61,General,Independent,NaN,19.0,5582.0,0.618576,NaN,902395.0,2024,8.0,5563.0
16412,Maharashtra,RATNAGIRI- SINDHUDURG,ASHOK GANGARAM PAWAR,M,61,General,Bahujan Mukti Party,NaN,36.0,5280.0,0.585110,NaN,902395.0,2024,9.0,5244.0
16413,Maharashtra,RATNAGIRI- SINDHUDURG,SURESH GOVINDRAO SHINDE,M,61,General,Sainik Samaj Party,NaN,38.0,2247.0,0.249004,NaN,902395.0,2024,10.0,2209.0

Column names for EVM/General votes was different in both datasets. Removing the extra column.

In [95]:
combined_df['EVM Votes'] = combined_df['EVM Votes'].fillna(combined_df['General Votes'])

In [96]:
combined_df.drop(['General Votes'], axis=1, inplace=True)

In [97]:
combined_df = combined_df[['State', 'Constituency', 'Candidate', 'Gender', 'Age', 'Category',
       'Party','EVM Votes', 'Postal Votes', 'Total Votes Received', 'Total Votes Polled',
       'Over Total Electors in Constituency (%)',
       'Over Total Votes Polled in Constituency (%)','Rank',
       'Year']]

In [98]:
combined_df

,State,Constituency,Candidate,Gender,Age,Category,Party,EVM Votes,Postal Votes,Total Votes Received,Total Votes Polled,Over Total Electors in Constituency (%),Over Total Votes Polled in Constituency (%),Rank,Year
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72,ST,TDP,336163.0,1938.0,338101.0,1451418.0,23.294530,31.356893,NaN,2019
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54,ST,BJP,17578.0,289.0,17867.0,1451418.0,1.231003,1.657060,NaN,2019
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26,ST,YSRCP,557561.0,4629.0,562190.0,1451418.0,38.733845,52.139840,NaN,2019
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46,ST,INC,17656.0,74.0,17730.0,1451418.0,1.221564,1.644354,NaN,2019
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49,ST,JnP,42245.0,549.0,42794.0,1451418.0,2.948427,3.968894,NaN,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16409,Maharashtra,RATNAGIRI- SINDHUDURG,AAYARE RAJENDRA LAHU,M,61,General,Bahujan Samaj Party,7796.0,60.0,7856.0,902395.0,0.870572,NaN,6.0,2024
16410,Maharashtra,RATNAGIRI- SINDHUDURG,SHAKIL SAWANT,M,61,General,Independent,6373.0,22.0,6395.0,902395.0,0.708670,NaN,7.0,2024
16411,Maharashtra,RATNAGIRI- SINDHUDURG,TAMBADE AMRUT ANANT (RAJAPURKAR),M,61,General,Independent,5563.0,19.0,5582.0,902395.0,0.618576,NaN,8.0,2024
16412,Maharashtra,RATNAGIRI- SINDHUDURG,ASHOK GANGARAM PAWAR,M,61,General,Bahujan Mukti Party,5244.0,36.0,5280.0,902395.0,0.585110,NaN,9.0,2024
16413,Maharashtra,RATNAGIRI- SINDHUDURG,SURESH GOVINDRAO SHINDE,M,61,General,Sainik Samaj Party,2209.0,38.0,2247.0,902395.0,0.249004,NaN,10.0,2024

In [99]:
combined_df.drop(columns=['EVM Votes'], inplace=True)

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\393888415.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df.drop(columns=['EVM Votes'], inplace=True)

In [100]:
combined_df.drop(index=9451, inplace=True) # uncontested candidate with null values

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\3580665919.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df.drop(index=9451, inplace=True) # uncontested candidate with null values

Adding missing ranks.

In [101]:
temp_df = combined_df

# Rank candidates within each constituency based on 'Total Votes Received'
temp_df['Rank'] = temp_df.groupby('Constituency')['Total Votes Received'].rank(ascending=False, method='min')

# Convert the ranks to integers, as ranks are typically whole numbers
temp_df['Rank'] = temp_df['Rank'].astype(int)

# Display the updated dataframe
temp_df

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\1770935824.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['Rank'] = temp_df.groupby('Constituency')['Total Votes Received'].rank(ascending=False, method='min')
C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\1770935824.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['Rank'] = temp_df['Rank'].astype(int)

,State,Constituency,Candidate,Gender,Age,Category,Party,Postal Votes,Total Votes Received,Total Votes Polled,Over Total Electors in Constituency (%),Over Total Votes Polled in Constituency (%),Rank,Year
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72,ST,TDP,1938.0,338101.0,1451418.0,23.294530,31.356893,2,2019
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54,ST,BJP,289.0,17867.0,1451418.0,1.231003,1.657060,4,2019
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26,ST,YSRCP,4629.0,562190.0,1451418.0,38.733845,52.139840,1,2019
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46,ST,INC,74.0,17730.0,1451418.0,1.221564,1.644354,5,2019
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49,ST,JnP,549.0,42794.0,1451418.0,2.948427,3.968894,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16409,Maharashtra,RATNAGIRI- SINDHUDURG,AAYARE RAJENDRA LAHU,M,61,General,Bahujan Samaj Party,60.0,7856.0,902395.0,0.870572,NaN,5,2024
16410,Maharashtra,RATNAGIRI- SINDHUDURG,SHAKIL SAWANT,M,61,General,Independent,22.0,6395.0,902395.0,0.708670,NaN,6,2024
16411,Maharashtra,RATNAGIRI- SINDHUDURG,TAMBADE AMRUT ANANT (RAJAPURKAR),M,61,General,Independent,19.0,5582.0,902395.0,0.618576,NaN,7,2024
16412,Maharashtra,RATNAGIRI- SINDHUDURG,ASHOK GANGARAM PAWAR,M,61,General,Bahujan Mukti Party,36.0,5280.0,902395.0,0.585110,NaN,8,2024
16413,Maharashtra,RATNAGIRI- SINDHUDURG,SURESH GOVINDRAO SHINDE,M,61,General,Sainik Samaj Party,38.0,2247.0,902395.0,0.249004,NaN,9,2024

In [102]:
cand_list_2024 = temp_df

In [103]:
combined_df.to_csv("../data/processed/candidate_list_turnout.csv", index=False)

### 3. Wrangling and cleaning candidate background datasets:

In [104]:
# Load the dataset
cand_bg_2024 = pd.read_csv("../data/raw/candidate_background_2024.csv")

In [105]:
cand_bg_2024.columns

Index(['Candidate', 'Party', 'Criminal Cases', 'Education', 'Age',
       'Total Assets', 'Liabilities', 'State'],
      dtype='object')

In [106]:
cand_bg_2024

,Candidate,Party,Criminal Cases,Education,Age,Total Assets,Liabilities,State
0,Anand Ramnath Arlekar,IND,0,10th Pass,58,"Rs 8,43,025 ~ 8 Lacs+","Rs 13,36,346 ~ 13 Lacs+",Andaman and Nicobar Islands
1,Bishnu Pada Ray,BJP,0,Graduate,73,"Rs 2,74,39,170 ~ 2 Crore+","Rs 3,02,788 ~ 3 Lacs+",Andaman and Nicobar Islands
2,D Ayyappan,CPI(M),0,Post Graduate,60,"Rs 1,32,87,710 ~ 1 Crore+","Rs 26,49,000 ~ 26 Lacs+",Andaman and Nicobar Islands
3,Dr Arun Kumar Mallik,BSP,0,Post Graduate,64,"Rs 11,18,72,135 ~ 11 Crore+",Rs 0 ~,Andaman and Nicobar Islands
4,K J B Selvaraj,AIADMK,0,Graduate,50,NaN,NaN,Andaman and Nicobar Islands
...,...,...,...,...,...,...,...,...
8333,Uttam Barik S/O Late Narayan Barik,IND,0,8th Pass,57,"Rs 7,82,132 ~ 7 Lacs+",Rs 0 ~,West Bengal
8334,Uttam Chatterjee,SUCI(C),0,Others,64,"Rs 78,44,105 ~ 78 Lacs+","Rs 2,00,000 ~ 2 Lacs+",West Bengal
8335,Vaskar Malik,IND,0,12th Pass,25,NaN,NaN,West Bengal
8336,Yasmin Islam,Social Democratic Party Of India,0,12th Pass,42,"Rs 34,36,438 ~ 34 Lacs+",Rs 0 ~,West Bengal
8337,Zubair Rabbani,SUCI(C),0,12th Pass,61,"Rs 19,127 ~ 19 Thou+",Rs 0 ~,West Bengal

We first need to change the units of Total Assets and Liabilities and convert them to integers

In [107]:
import re
def clean_currency(value):
    if pd.isnull(value) or value.strip() == '':  # Handle NaN or empty values
        return 0
    
    # Split the string at the '~' symbol and take the part before it
    value = value.split('~')[0]
    
    # Remove non-numeric characters
    cleaned_value = re.sub(r'[^\d]', '', value)
    
    # If cleaned_value is empty after removing non-numeric characters, return 0
    if cleaned_value == '':
        return 0
    
    return int(cleaned_value)

In [108]:

# Apply the function to the 'Total Assets' and 'Liabilities' columns
cand_bg_2024['Total Assets'] = cand_bg_2024['Total Assets'].apply(clean_currency)
cand_bg_2024['Liabilities'] = cand_bg_2024['Liabilities'].apply(clean_currency)

In [109]:
cand_bg_2024

,Candidate,Party,Criminal Cases,Education,Age,Total Assets,Liabilities,State
0,Anand Ramnath Arlekar,IND,0,10th Pass,58,843025,1336346,Andaman and Nicobar Islands
1,Bishnu Pada Ray,BJP,0,Graduate,73,27439170,302788,Andaman and Nicobar Islands
2,D Ayyappan,CPI(M),0,Post Graduate,60,13287710,2649000,Andaman and Nicobar Islands
3,Dr Arun Kumar Mallik,BSP,0,Post Graduate,64,111872135,0,Andaman and Nicobar Islands
4,K J B Selvaraj,AIADMK,0,Graduate,50,0,0,Andaman and Nicobar Islands
...,...,...,...,...,...,...,...,...
8333,Uttam Barik S/O Late Narayan Barik,IND,0,8th Pass,57,782132,0,West Bengal
8334,Uttam Chatterjee,SUCI(C),0,Others,64,7844105,200000,West Bengal
8335,Vaskar Malik,IND,0,12th Pass,25,0,0,West Bengal
8336,Yasmin Islam,Social Democratic Party Of India,0,12th Pass,42,3436438,0,West Bengal
8337,Zubair Rabbani,SUCI(C),0,12th Pass,61,19127,0,West Bengal

In [110]:
cand_bg_2024.columns

Index(['Candidate', 'Party', 'Criminal Cases', 'Education', 'Age',
       'Total Assets', 'Liabilities', 'State'],
      dtype='object')

In [111]:
cand_bg_2024.rename(columns={
    'Candidate': 'Candidate Name',
}, inplace=True)
cand_bg_2024 = cand_bg_2024[['Candidate Name', 'Party', 'Age', 'State', 'Criminal Cases', 'Education', 'Total Assets', 'Liabilities']]
cand_bg_2024

,Candidate Name,Party,Age,State,Criminal Cases,Education,Total Assets,Liabilities
0,Anand Ramnath Arlekar,IND,58,Andaman and Nicobar Islands,0,10th Pass,843025,1336346
1,Bishnu Pada Ray,BJP,73,Andaman and Nicobar Islands,0,Graduate,27439170,302788
2,D Ayyappan,CPI(M),60,Andaman and Nicobar Islands,0,Post Graduate,13287710,2649000
3,Dr Arun Kumar Mallik,BSP,64,Andaman and Nicobar Islands,0,Post Graduate,111872135,0
4,K J B Selvaraj,AIADMK,50,Andaman and Nicobar Islands,0,Graduate,0,0
...,...,...,...,...,...,...,...,...
8333,Uttam Barik S/O Late Narayan Barik,IND,57,West Bengal,0,8th Pass,782132,0
8334,Uttam Chatterjee,SUCI(C),64,West Bengal,0,Others,7844105,200000
8335,Vaskar Malik,IND,25,West Bengal,0,12th Pass,0,0
8336,Yasmin Islam,Social Democratic Party Of India,42,West Bengal,0,12th Pass,3436438,0
8337,Zubair Rabbani,SUCI(C),61,West Bengal,0,12th Pass,19127,0

Background data for 2019 candidates:

In [112]:
cand_bg_2019 = pd.read_csv("../data/raw/candidate_background_2019.csv")

In [113]:
cand_bg_2019

,Candidate,Party,Criminal Cases,Education,Age,Total Assets,Liabilities,State
0,Ayan Mandal,AITC,0,Graduate,30,"Rs 72,70,440 ~ 72 Lacs+","Rs 15,00,000 ~ 15 Lacs+",Andaman and Nicobar Islands
1,C G Saji Kumar,All India Hindustan Congress Party,0,12th Pass,48,"Rs 1,20,000 ~ 1 Lacs+",Rs 0 ~,Andaman and Nicobar Islands
2,C U Rasheed,IND,0,12th Pass,34,"Rs 2,02,808 ~ 2 Lacs+","Rs 17,00,000 ~ 17 Lacs+",Andaman and Nicobar Islands
3,Gour Chandra Majumder,IND,0,Graduate,52,"Rs 60,62,000 ~ 60 Lacs+",Rs 0 ~,Andaman and Nicobar Islands
4,Henry,IND,0,10th Pass,50,NaN,NaN,Andaman and Nicobar Islands
...,...,...,...,...,...,...,...,...
7501,Surendra Kumar Upadhayay,UKD,0,Graduate,Unknown,"Rs 42,78,300 ~ 42 Lacs+","Rs 21,00,000 ~ 21 Lacs+",Uttarakhand
7502,Tirath Singh Rawat,BJP,0,Post Graduate,55,"Rs 1,50,32,657 ~ 1 Crore+","Rs 35,00,000 ~ 35 Lacs+",Uttarakhand
7503,Tribirendra Singh Rawat,Uttarakhand Kranti Dal (Democratic),0,12th Pass,30,"Rs 39,41,321 ~ 39 Lacs+",Rs 0 ~,Uttarakhand
7504,Vimla Arya,UTTARAKHAND PARIVARTAN PARTY,0,Graduate,32,NaN,NaN,Uttarakhand
7505,Vinod Prasad Notiyal,IND,0,8th Pass,43,"Rs 16,85,354 ~ 16 Lacs+",Rs 0 ~,Uttarakhand

In [114]:
# Apply the function to the 'Total Assets' and 'Liabilities' columns
cand_bg_2019['Total Assets'] = cand_bg_2019['Total Assets'].apply(clean_currency)
cand_bg_2019['Liabilities'] = cand_bg_2019['Liabilities'].apply(clean_currency)

In [115]:
cand_bg_2019

,Candidate,Party,Criminal Cases,Education,Age,Total Assets,Liabilities,State
0,Ayan Mandal,AITC,0,Graduate,30,7270440,1500000,Andaman and Nicobar Islands
1,C G Saji Kumar,All India Hindustan Congress Party,0,12th Pass,48,120000,0,Andaman and Nicobar Islands
2,C U Rasheed,IND,0,12th Pass,34,202808,1700000,Andaman and Nicobar Islands
3,Gour Chandra Majumder,IND,0,Graduate,52,6062000,0,Andaman and Nicobar Islands
4,Henry,IND,0,10th Pass,50,0,0,Andaman and Nicobar Islands
...,...,...,...,...,...,...,...,...
7501,Surendra Kumar Upadhayay,UKD,0,Graduate,Unknown,4278300,2100000,Uttarakhand
7502,Tirath Singh Rawat,BJP,0,Post Graduate,55,15032657,3500000,Uttarakhand
7503,Tribirendra Singh Rawat,Uttarakhand Kranti Dal (Democratic),0,12th Pass,30,3941321,0,Uttarakhand
7504,Vimla Arya,UTTARAKHAND PARIVARTAN PARTY,0,Graduate,32,0,0,Uttarakhand
7505,Vinod Prasad Notiyal,IND,0,8th Pass,43,1685354,0,Uttarakhand

In [116]:
cand_bg_2019.rename(columns={
    'Candidate': 'Candidate Name',
}, inplace=True)
cand_bg_2019 = cand_bg_2019[['Candidate Name', 'Party', 'Age', 'State', 'Criminal Cases', 'Education', 'Total Assets', 'Liabilities']]
cand_bg_2019

,Candidate Name,Party,Age,State,Criminal Cases,Education,Total Assets,Liabilities
0,Ayan Mandal,AITC,30,Andaman and Nicobar Islands,0,Graduate,7270440,1500000
1,C G Saji Kumar,All India Hindustan Congress Party,48,Andaman and Nicobar Islands,0,12th Pass,120000,0
2,C U Rasheed,IND,34,Andaman and Nicobar Islands,0,12th Pass,202808,1700000
3,Gour Chandra Majumder,IND,52,Andaman and Nicobar Islands,0,Graduate,6062000,0
4,Henry,IND,50,Andaman and Nicobar Islands,0,10th Pass,0,0
...,...,...,...,...,...,...,...,...
7501,Surendra Kumar Upadhayay,UKD,Unknown,Uttarakhand,0,Graduate,4278300,2100000
7502,Tirath Singh Rawat,BJP,55,Uttarakhand,0,Post Graduate,15032657,3500000
7503,Tribirendra Singh Rawat,Uttarakhand Kranti Dal (Democratic),30,Uttarakhand,0,12th Pass,3941321,0
7504,Vimla Arya,UTTARAKHAND PARIVARTAN PARTY,32,Uttarakhand,0,Graduate,0,0
7505,Vinod Prasad Notiyal,IND,43,Uttarakhand,0,8th Pass,1685354,0

In [117]:
cand_bg_2019.columns

Index(['Candidate Name', 'Party', 'Age', 'State', 'Criminal Cases',
       'Education', 'Total Assets', 'Liabilities'],
      dtype='object')

Merging background data DFs:

In [118]:
cand_bg_2019['Year'] = 2019
cand_bg_2024['Year'] = 2024

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\964055193.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cand_bg_2019['Year'] = 2019
C:\Users\ujjwa\AppData\Local\Temp\ipykernel_16056\964055193.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cand_bg_2024['Year'] = 2024

In [119]:
# Concatenate the dataframes
combined_bg_df = pd.concat([cand_bg_2019, cand_bg_2024], ignore_index=True)

In [120]:
combined_bg_df

,Candidate Name,Party,Age,State,Criminal Cases,Education,Total Assets,Liabilities,Year
0,Ayan Mandal,AITC,30,Andaman and Nicobar Islands,0,Graduate,7270440,1500000,2019
1,C G Saji Kumar,All India Hindustan Congress Party,48,Andaman and Nicobar Islands,0,12th Pass,120000,0,2019
2,C U Rasheed,IND,34,Andaman and Nicobar Islands,0,12th Pass,202808,1700000,2019
3,Gour Chandra Majumder,IND,52,Andaman and Nicobar Islands,0,Graduate,6062000,0,2019
4,Henry,IND,50,Andaman and Nicobar Islands,0,10th Pass,0,0,2019
...,...,...,...,...,...,...,...,...,...
15839,Uttam Barik S/O Late Narayan Barik,IND,57,West Bengal,0,8th Pass,782132,0,2024
15840,Uttam Chatterjee,SUCI(C),64,West Bengal,0,Others,7844105,200000,2024
15841,Vaskar Malik,IND,25,West Bengal,0,12th Pass,0,0,2024
15842,Yasmin Islam,Social Democratic Party Of India,42,West Bengal,0,12th Pass,3436438,0,2024
15843,Zubair Rabbani,SUCI(C),61,West Bengal,0,12th Pass,19127,0,2024

In [121]:
combined_bg_df.to_csv("../data/processed/candidate_background.csv", index=False)