In [27]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

In [28]:
# Set up the Selenium WebDriver
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

# Navigate to the page
url = "https://www.indiavotes.com/lok-sabha/2024/all-states/18/0"
driver.get(url)

In [29]:
# Wait for the page to load (adjust the time as needed)
time.sleep(5)

# Get the page source after JavaScript has run
html = driver.page_source

In [30]:
# Use pandas to read the HTML
dfs = pd.read_html(html)

# Print the number of tables found
print(f"Number of tables found: {len(dfs)}")

C:\Users\ujjwa\AppData\Local\Temp\ipykernel_22480\1625594766.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs = pd.read_html(html)

Number of tables found: 3

In [31]:
dfs[0]

               Party              Seats            Votes %         Unnamed: 3
0                BJP                240               36.9                NaN
1                INC                 99               21.4                NaN
2                 SP                 37                4.6                NaN
3               AITC                 29                4.4                NaN
4                DMK                 22                1.8                NaN
5                IND                  7                2.8                NaN
6             Others                109               28.1                NaN
7  All Party Results  All Party Results  All Party Results  All Party Results

In [32]:
dfs[1]

,Alliance,Seats,Votes %,Contested Voteshare
0,NDA,292,43.4,44
1,INDIA,230,36.7,37.2
2,Alliances Partywise Details,Alliances Partywise Details,Alliances Partywise Details,Alliances Partywise Details

In [33]:
dfs[2]

,#,Unnamed: 1_level_0,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0,Unnamed: 10_level_0,Unnamed: 11_level_0
,#,PC Name,No,Type,State,Winning Candidate,Party,Electors,Votes,Turnout,Margin,Margin %
0,1,Adilabad,1,ST,Telangana,Godam Nagesh,Bharatiya Janta Party,1650175,1235597,74.9 %,90652.0,7.3%
1,2,Agra,18,SC,Uttar Pradesh [2000 Onwards],Prof S P Singh Baghel,Bharatiya Janta Party,2072685,1123779,54.2 %,271294.0,24.1%
2,3,Ahmadnagar,37,GEN,Maharashtra,Nilesh Dnyandev Lanke,Nationalist Congress Party – Sharadchandra Pawar,1981866,1325477,66.9 %,28929.0,2.2%
3,4,Ahmedabad East,7,GEN,Gujarat,Hasmukhbhai Patel (H.S.PATEL),Bharatiya Janta Party,2038162,1128339,55.4 %,461755.0,40.9%
4,5,Ahmedabad West,8,SC,Gujarat,Dineshbhai Makwana (ADVOCATE),Bharatiya Janta Party,1726987,966646,56.0 %,286437.0,29.6%
...,...,...,...,...,...,...,...,...,...,...,...,...
538,539,Wardha,8,GEN,Maharashtra,Amar Sharadrao Kale,Nationalist Congress Party – Sharadchandra Pawar,1682771,1095012,65.1 %,81648.0,7.5%
539,540,Wayanad,4,GEN,Kerala,Rahul Gandhi,Indian National Congress,1462423,1084653,74.2 %,364422.0,33.6%
540,541,West Delhi,6,GEN,Delhi [1977 Onwards],Kamaljeet Sehrawat,Bharatiya Janta Party,2587977,1524494,58.9 %,199013.0,13.1%
541,542,Yavatmal-Washi,14,GEN,Maharashtra,Sanjay Uttamrao Deshmukh,Shiv Sena (Uddhav Balasaheb Thackrey),1940916,1225530,63.1 %,94473.0,7.7%
542,543,Zahirabad,5,GEN,Telangana,Suresh Kumar Shetkar,Indian National Congress,1641410,1236593,75.3 %,46188.0,3.7%

In [24]:
election_data = dfs[2]
election_data

,#,Unnamed: 1_level_0,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0,Unnamed: 10_level_0,Unnamed: 11_level_0
,#,PC Name,No,Type,State,Winning Candidate,Party,Electors,Votes,Turnout,Margin,Margin %
0,1,Adilabad,1,ST,Telangana,Godam Nagesh,Bharatiya Janta Party,1650175,1235597,74.9 %,90652.0,7.3%
1,2,Agra,18,SC,Uttar Pradesh [2000 Onwards],Prof S P Singh Baghel,Bharatiya Janta Party,2072685,1123779,54.2 %,271294.0,24.1%
2,3,Ahmadnagar,37,GEN,Maharashtra,Nilesh Dnyandev Lanke,Nationalist Congress Party – Sharadchandra Pawar,1981866,1325477,66.9 %,28929.0,2.2%
3,4,Ahmedabad East,7,GEN,Gujarat,Hasmukhbhai Patel (H.S.PATEL),Bharatiya Janta Party,2038162,1128339,55.4 %,461755.0,40.9%
4,5,Ahmedabad West,8,SC,Gujarat,Dineshbhai Makwana (ADVOCATE),Bharatiya Janta Party,1726987,966646,56.0 %,286437.0,29.6%
...,...,...,...,...,...,...,...,...,...,...,...,...
538,539,Wardha,8,GEN,Maharashtra,Amar Sharadrao Kale,Nationalist Congress Party – Sharadchandra Pawar,1682771,1095012,65.1 %,81648.0,7.5%
539,540,Wayanad,4,GEN,Kerala,Rahul Gandhi,Indian National Congress,1462423,1084653,74.2 %,364422.0,33.6%
540,541,West Delhi,6,GEN,Delhi [1977 Onwards],Kamaljeet Sehrawat,Bharatiya Janta Party,2587977,1524494,58.9 %,199013.0,13.1%
541,542,Yavatmal-Washi,14,GEN,Maharashtra,Sanjay Uttamrao Deshmukh,Shiv Sena (Uddhav Balasaheb Thackrey),1940916,1225530,63.1 %,94473.0,7.7%
542,543,Zahirabad,5,GEN,Telangana,Suresh Kumar Shetkar,Indian National Congress,1641410,1236593,75.3 %,46188.0,3.7%

In [25]:
election_data.columns

MultiIndex([(                  '#',                 '#'),
            ( 'Unnamed: 1_level_0',           'PC Name'),
            ( 'Unnamed: 2_level_0',                'No'),
            ( 'Unnamed: 3_level_0',              'Type'),
            ( 'Unnamed: 4_level_0',             'State'),
            ( 'Unnamed: 5_level_0', 'Winning Candidate'),
            ( 'Unnamed: 6_level_0',             'Party'),
            ( 'Unnamed: 7_level_0',          'Electors'),
            ( 'Unnamed: 8_level_0',             'Votes'),
            ( 'Unnamed: 9_level_0',           'Turnout'),
            ('Unnamed: 10_level_0',            'Margin'),
            ('Unnamed: 11_level_0',          'Margin %')],
           )

In [34]:
election_data.to_csv('election_data.csv', index=False)